// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.AdbBindingRequest}
 */
@com.google.protobuf.Generated
public  final class AdbBindingRequest extends
    com.google.protobuf.GeneratedMessageLite<
        AdbBindingRequest, AdbBindingRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.AdbBindingRequest)
    AdbBindingRequestOrBuilder {
  private AdbBindingRequest() {
    adbSerial_ = "";
    nonce_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int ADB_SERIAL_FIELD_NUMBER = 1;
  private java.lang.String adbSerial_;
  /**
   * <code>string adb_serial = 1;</code>
   * @return The adbSerial.
   */
  @java.lang.Override
  public java.lang.String getAdbSerial() {
    return adbSerial_;
  }
  /**
   * <code>string adb_serial = 1;</code>
   * @return The bytes for adbSerial.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAdbSerialBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(adbSerial_);
  }
  /**
   * <code>string adb_serial = 1;</code>
   * @param value The adbSerial to set.
   */
  private void setAdbSerial(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    adbSerial_ = value;
  }
  /**
   * <code>string adb_serial = 1;</code>
   */
  private void clearAdbSerial() {

    adbSerial_ = getDefaultInstance().getAdbSerial();
  }
  /**
   * <code>string adb_serial = 1;</code>
   * @param value The bytes for adbSerial to set.
   */
  private void setAdbSerialBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    adbSerial_ = value.toStringUtf8();

  }

  public static final int NONCE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString nonce_;
  /**
   * <code>bytes nonce = 2;</code>
   * @return The nonce.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNonce() {
    return nonce_;
  }
  /**
   * <code>bytes nonce = 2;</code>
   * @param value The nonce to set.
   */
  private void setNonce(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    nonce_ = value;
  }
  /**
   * <code>bytes nonce = 2;</code>
   */
  private void clearNonce() {

    nonce_ = getDefaultInstance().getNonce();
  }

  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.AdbBindingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.AdbBindingRequest)
      com.xopmc.galaxybridge.protocol.v1.AdbBindingRequestOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string adb_serial = 1;</code>
     * @return The adbSerial.
     */
    @java.lang.Override
    public java.lang.String getAdbSerial() {
      return instance.getAdbSerial();
    }
    /**
     * <code>string adb_serial = 1;</code>
     * @return The bytes for adbSerial.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAdbSerialBytes() {
      return instance.getAdbSerialBytes();
    }
    /**
     * <code>string adb_serial = 1;</code>
     * @param value The adbSerial to set.
     * @return This builder for chaining.
     */
    public Builder setAdbSerial(
        java.lang.String value) {
      copyOnWrite();
      instance.setAdbSerial(value);
      return this;
    }
    /**
     * <code>string adb_serial = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdbSerial() {
      copyOnWrite();
      instance.clearAdbSerial();
      return this;
    }
    /**
     * <code>string adb_serial = 1;</code>
     * @param value The bytes for adbSerial to set.
     * @return This builder for chaining.
     */
    public Builder setAdbSerialBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAdbSerialBytes(value);
      return this;
    }

    /**
     * <code>bytes nonce = 2;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNonce() {
      return instance.getNonce();
    }
    /**
     * <code>bytes nonce = 2;</code>
     * @param value The nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonce(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNonce(value);
      return this;
    }
    /**
     * <code>bytes nonce = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonce() {
      copyOnWrite();
      instance.clearNonce();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.AdbBindingRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "adbSerial_",
            "nonce_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\n" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.AdbBindingRequest)
  private static final com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest DEFAULT_INSTANCE;
  static {
    AdbBindingRequest defaultInstance = new AdbBindingRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AdbBindingRequest.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AdbBindingRequest> PARSER;

  public static com.google.protobuf.Parser<AdbBindingRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

