// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface AdbBindingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.AdbBindingRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string adb_serial = 1;</code>
   * @return The adbSerial.
   */
  java.lang.String getAdbSerial();
  /**
   * <code>string adb_serial = 1;</code>
   * @return The bytes for adbSerial.
   */
  com.google.protobuf.ByteString
      getAdbSerialBytes();

  /**
   * <code>bytes nonce = 2;</code>
   * @return The nonce.
   */
  com.google.protobuf.ByteString getNonce();
}
