// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf enum {@code galaxybridge.v1.CallState}
 */
@com.google.protobuf.Generated
public enum CallState
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>CALL_STATE_UNSPECIFIED = 0;</code>
   */
  CALL_STATE_UNSPECIFIED(0),
  /**
   * <code>CALL_STATE_IDLE = 1;</code>
   */
  CALL_STATE_IDLE(1),
  /**
   * <code>CALL_STATE_RINGING = 2;</code>
   */
  CALL_STATE_RINGING(2),
  /**
   * <code>CALL_STATE_DIALING = 3;</code>
   */
  CALL_STATE_DIALING(3),
  /**
   * <code>CALL_STATE_ACTIVE = 4;</code>
   */
  CALL_STATE_ACTIVE(4),
  /**
   * <code>CALL_STATE_ENDED = 5;</code>
   */
  CALL_STATE_ENDED(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CALL_STATE_UNSPECIFIED = 0;</code>
   */
  public static final int CALL_STATE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>CALL_STATE_IDLE = 1;</code>
   */
  public static final int CALL_STATE_IDLE_VALUE = 1;
  /**
   * <code>CALL_STATE_RINGING = 2;</code>
   */
  public static final int CALL_STATE_RINGING_VALUE = 2;
  /**
   * <code>CALL_STATE_DIALING = 3;</code>
   */
  public static final int CALL_STATE_DIALING_VALUE = 3;
  /**
   * <code>CALL_STATE_ACTIVE = 4;</code>
   */
  public static final int CALL_STATE_ACTIVE_VALUE = 4;
  /**
   * <code>CALL_STATE_ENDED = 5;</code>
   */
  public static final int CALL_STATE_ENDED_VALUE = 5;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CallState valueOf(int value) {
    return forNumber(value);
  }

  public static CallState forNumber(int value) {
    switch (value) {
      case 0: return CALL_STATE_UNSPECIFIED;
      case 1: return CALL_STATE_IDLE;
      case 2: return CALL_STATE_RINGING;
      case 3: return CALL_STATE_DIALING;
      case 4: return CALL_STATE_ACTIVE;
      case 5: return CALL_STATE_ENDED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CallState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CallState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CallState>() {
          @java.lang.Override
          public CallState findValueByNumber(int number) {
            return CallState.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return CallStateVerifier.INSTANCE;
  }

  private static final class CallStateVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new CallStateVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return CallState.forNumber(number) != null;
          }
        };

  private final int value;

  private CallState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:galaxybridge.v1.CallState)
}

