// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.CallEvent}
 */
@com.google.protobuf.Generated
public  final class CallEvent extends
    com.google.protobuf.GeneratedMessageLite<
        CallEvent, CallEvent.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.CallEvent)
    CallEventOrBuilder {
  private CallEvent() {
    callId_ = "";
    address_ = "";
    displayName_ = "";
  }
  public static final int CALL_ID_FIELD_NUMBER = 1;
  private java.lang.String callId_;
  /**
   * <code>string call_id = 1;</code>
   * @return The callId.
   */
  @java.lang.Override
  public java.lang.String getCallId() {
    return callId_;
  }
  /**
   * <code>string call_id = 1;</code>
   * @return The bytes for callId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCallIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(callId_);
  }
  /**
   * <code>string call_id = 1;</code>
   * @param value The callId to set.
   */
  private void setCallId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    callId_ = value;
  }
  /**
   * <code>string call_id = 1;</code>
   */
  private void clearCallId() {

    callId_ = getDefaultInstance().getCallId();
  }
  /**
   * <code>string call_id = 1;</code>
   * @param value The bytes for callId to set.
   */
  private void setCallIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    callId_ = value.toStringUtf8();

  }

  public static final int ADDRESS_FIELD_NUMBER = 2;
  private java.lang.String address_;
  /**
   * <code>string address = 2;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    return address_;
  }
  /**
   * <code>string address = 2;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(address_);
  }
  /**
   * <code>string address = 2;</code>
   * @param value The address to set.
   */
  private void setAddress(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    address_ = value;
  }
  /**
   * <code>string address = 2;</code>
   */
  private void clearAddress() {

    address_ = getDefaultInstance().getAddress();
  }
  /**
   * <code>string address = 2;</code>
   * @param value The bytes for address to set.
   */
  private void setAddressBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    address_ = value.toStringUtf8();

  }

  public static final int DISPLAY_NAME_FIELD_NUMBER = 3;
  private java.lang.String displayName_;
  /**
   * <code>string display_name = 3;</code>
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    return displayName_;
  }
  /**
   * <code>string display_name = 3;</code>
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(displayName_);
  }
  /**
   * <code>string display_name = 3;</code>
   * @param value The displayName to set.
   */
  private void setDisplayName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    displayName_ = value;
  }
  /**
   * <code>string display_name = 3;</code>
   */
  private void clearDisplayName() {

    displayName_ = getDefaultInstance().getDisplayName();
  }
  /**
   * <code>string display_name = 3;</code>
   * @param value The bytes for displayName to set.
   */
  private void setDisplayNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    displayName_ = value.toStringUtf8();

  }

  public static final int STATE_FIELD_NUMBER = 4;
  private int state_;
  /**
   * <code>.galaxybridge.v1.CallState state = 4;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override
  public int getStateValue() {
    return state_;
  }
  /**
   * <code>.galaxybridge.v1.CallState state = 4;</code>
   * @return The state.
   */
  @java.lang.Override
  public com.xopmc.galaxybridge.protocol.v1.CallState getState() {
    com.xopmc.galaxybridge.protocol.v1.CallState result = com.xopmc.galaxybridge.protocol.v1.CallState.forNumber(state_);
    return result == null ? com.xopmc.galaxybridge.protocol.v1.CallState.UNRECOGNIZED : result;
  }
  /**
   * <code>.galaxybridge.v1.CallState state = 4;</code>
   * @param value The enum numeric value on the wire for state to set.
   */
  private void setStateValue(int value) {
      state_ = value;
  }
  /**
   * <code>.galaxybridge.v1.CallState state = 4;</code>
   * @param value The state to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setState(com.xopmc.galaxybridge.protocol.v1.CallState value) {
    state_ = value.getNumber();

  }
  /**
   * <code>.galaxybridge.v1.CallState state = 4;</code>
   */
  private void clearState() {

    state_ = 0;
  }

  public static final int INCOMING_FIELD_NUMBER = 5;
  private boolean incoming_;
  /**
   * <code>bool incoming = 5;</code>
   * @return The incoming.
   */
  @java.lang.Override
  public boolean getIncoming() {
    return incoming_;
  }
  /**
   * <code>bool incoming = 5;</code>
   * @param value The incoming to set.
   */
  private void setIncoming(boolean value) {
    
    incoming_ = value;
  }
  /**
   * <code>bool incoming = 5;</code>
   */
  private void clearIncoming() {

    incoming_ = false;
  }

  public static final int TIMESTAMP_UNIX_MS_FIELD_NUMBER = 6;
  private long timestampUnixMs_;
  /**
   * <code>int64 timestamp_unix_ms = 6;</code>
   * @return The timestampUnixMs.
   */
  @java.lang.Override
  public long getTimestampUnixMs() {
    return timestampUnixMs_;
  }
  /**
   * <code>int64 timestamp_unix_ms = 6;</code>
   * @param value The timestampUnixMs to set.
   */
  private void setTimestampUnixMs(long value) {
    
    timestampUnixMs_ = value;
  }
  /**
   * <code>int64 timestamp_unix_ms = 6;</code>
   */
  private void clearTimestampUnixMs() {

    timestampUnixMs_ = 0L;
  }

  public static final int DURATION_SECONDS_FIELD_NUMBER = 7;
  private int durationSeconds_;
  /**
   * <code>uint32 duration_seconds = 7;</code>
   * @return The durationSeconds.
   */
  @java.lang.Override
  public int getDurationSeconds() {
    return durationSeconds_;
  }
  /**
   * <code>uint32 duration_seconds = 7;</code>
   * @param value The durationSeconds to set.
   */
  private void setDurationSeconds(int value) {
    
    durationSeconds_ = value;
  }
  /**
   * <code>uint32 duration_seconds = 7;</code>
   */
  private void clearDurationSeconds() {

    durationSeconds_ = 0;
  }

  public static final int HISTORY_FIELD_NUMBER = 8;
  private boolean history_;
  /**
   * <code>bool history = 8;</code>
   * @return The history.
   */
  @java.lang.Override
  public boolean getHistory() {
    return history_;
  }
  /**
   * <code>bool history = 8;</code>
   * @param value The history to set.
   */
  private void setHistory(boolean value) {
    
    history_ = value;
  }
  /**
   * <code>bool history = 8;</code>
   */
  private void clearHistory() {

    history_ = false;
  }

  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CallEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.CallEvent prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.CallEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.CallEvent, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.CallEvent)
      com.xopmc.galaxybridge.protocol.v1.CallEventOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.CallEvent.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string call_id = 1;</code>
     * @return The callId.
     */
    @java.lang.Override
    public java.lang.String getCallId() {
      return instance.getCallId();
    }
    /**
     * <code>string call_id = 1;</code>
     * @return The bytes for callId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCallIdBytes() {
      return instance.getCallIdBytes();
    }
    /**
     * <code>string call_id = 1;</code>
     * @param value The callId to set.
     * @return This builder for chaining.
     */
    public Builder setCallId(
        java.lang.String value) {
      copyOnWrite();
      instance.setCallId(value);
      return this;
    }
    /**
     * <code>string call_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCallId() {
      copyOnWrite();
      instance.clearCallId();
      return this;
    }
    /**
     * <code>string call_id = 1;</code>
     * @param value The bytes for callId to set.
     * @return This builder for chaining.
     */
    public Builder setCallIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCallIdBytes(value);
      return this;
    }

    /**
     * <code>string address = 2;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      return instance.getAddress();
    }
    /**
     * <code>string address = 2;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      return instance.getAddressBytes();
    }
    /**
     * <code>string address = 2;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      copyOnWrite();
      instance.setAddress(value);
      return this;
    }
    /**
     * <code>string address = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      copyOnWrite();
      instance.clearAddress();
      return this;
    }
    /**
     * <code>string address = 2;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAddressBytes(value);
      return this;
    }

    /**
     * <code>string display_name = 3;</code>
     * @return The displayName.
     */
    @java.lang.Override
    public java.lang.String getDisplayName() {
      return instance.getDisplayName();
    }
    /**
     * <code>string display_name = 3;</code>
     * @return The bytes for displayName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      return instance.getDisplayNameBytes();
    }
    /**
     * <code>string display_name = 3;</code>
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(
        java.lang.String value) {
      copyOnWrite();
      instance.setDisplayName(value);
      return this;
    }
    /**
     * <code>string display_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      copyOnWrite();
      instance.clearDisplayName();
      return this;
    }
    /**
     * <code>string display_name = 3;</code>
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDisplayNameBytes(value);
      return this;
    }

    /**
     * <code>.galaxybridge.v1.CallState state = 4;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override
    public int getStateValue() {
      return instance.getStateValue();
    }
    /**
     * <code>.galaxybridge.v1.CallState state = 4;</code>
     * @param value The state to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      copyOnWrite();
      instance.setStateValue(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.CallState state = 4;</code>
     * @return The state.
     */
    @java.lang.Override
    public com.xopmc.galaxybridge.protocol.v1.CallState getState() {
      return instance.getState();
    }
    /**
     * <code>.galaxybridge.v1.CallState state = 4;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setState(com.xopmc.galaxybridge.protocol.v1.CallState value) {
      copyOnWrite();
      instance.setState(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.CallState state = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }

    /**
     * <code>bool incoming = 5;</code>
     * @return The incoming.
     */
    @java.lang.Override
    public boolean getIncoming() {
      return instance.getIncoming();
    }
    /**
     * <code>bool incoming = 5;</code>
     * @param value The incoming to set.
     * @return This builder for chaining.
     */
    public Builder setIncoming(boolean value) {
      copyOnWrite();
      instance.setIncoming(value);
      return this;
    }
    /**
     * <code>bool incoming = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncoming() {
      copyOnWrite();
      instance.clearIncoming();
      return this;
    }

    /**
     * <code>int64 timestamp_unix_ms = 6;</code>
     * @return The timestampUnixMs.
     */
    @java.lang.Override
    public long getTimestampUnixMs() {
      return instance.getTimestampUnixMs();
    }
    /**
     * <code>int64 timestamp_unix_ms = 6;</code>
     * @param value The timestampUnixMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampUnixMs(long value) {
      copyOnWrite();
      instance.setTimestampUnixMs(value);
      return this;
    }
    /**
     * <code>int64 timestamp_unix_ms = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampUnixMs() {
      copyOnWrite();
      instance.clearTimestampUnixMs();
      return this;
    }

    /**
     * <code>uint32 duration_seconds = 7;</code>
     * @return The durationSeconds.
     */
    @java.lang.Override
    public int getDurationSeconds() {
      return instance.getDurationSeconds();
    }
    /**
     * <code>uint32 duration_seconds = 7;</code>
     * @param value The durationSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setDurationSeconds(int value) {
      copyOnWrite();
      instance.setDurationSeconds(value);
      return this;
    }
    /**
     * <code>uint32 duration_seconds = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationSeconds() {
      copyOnWrite();
      instance.clearDurationSeconds();
      return this;
    }

    /**
     * <code>bool history = 8;</code>
     * @return The history.
     */
    @java.lang.Override
    public boolean getHistory() {
      return instance.getHistory();
    }
    /**
     * <code>bool history = 8;</code>
     * @param value The history to set.
     * @return This builder for chaining.
     */
    public Builder setHistory(boolean value) {
      copyOnWrite();
      instance.setHistory(value);
      return this;
    }
    /**
     * <code>bool history = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearHistory() {
      copyOnWrite();
      instance.clearHistory();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.CallEvent)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.CallEvent();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "callId_",
            "address_",
            "displayName_",
            "state_",
            "incoming_",
            "timestampUnixMs_",
            "durationSeconds_",
            "history_",
          };
          java.lang.String info =
              "\u0000\b\u0000\u0000\u0001\b\b\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\f\u0005\u0007\u0006\u0002\u0007\u000b\b\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.CallEvent> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.CallEvent.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.CallEvent>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.CallEvent)
  private static final com.xopmc.galaxybridge.protocol.v1.CallEvent DEFAULT_INSTANCE;
  static {
    CallEvent defaultInstance = new CallEvent();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CallEvent.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.CallEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CallEvent> PARSER;

  public static com.google.protobuf.Parser<CallEvent> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

