// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface CameraStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.CameraStatus)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
   * @return The state.
   */
  com.xopmc.galaxybridge.protocol.v1.CameraCaptureState getState();

  /**
   * <code>string reason_code = 3;</code>
   * @return The reasonCode.
   */
  java.lang.String getReasonCode();
  /**
   * <code>string reason_code = 3;</code>
   * @return The bytes for reasonCode.
   */
  com.google.protobuf.ByteString
      getReasonCodeBytes();

  /**
   * <code>bool retryable = 4;</code>
   * @return The retryable.
   */
  boolean getRetryable();
}
