// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.CameraStatus}
 */
@com.google.protobuf.Generated
public  final class CameraStatus extends
    com.google.protobuf.GeneratedMessageLite<
        CameraStatus, CameraStatus.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.CameraStatus)
    CameraStatusOrBuilder {
  private CameraStatus() {
    requestId_ = "";
    reasonCode_ = "";
  }
  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private java.lang.String requestId_;
  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    return requestId_;
  }
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(requestId_);
  }
  /**
   * <code>string request_id = 1;</code>
   * @param value The requestId to set.
   */
  private void setRequestId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    requestId_ = value;
  }
  /**
   * <code>string request_id = 1;</code>
   */
  private void clearRequestId() {

    requestId_ = getDefaultInstance().getRequestId();
  }
  /**
   * <code>string request_id = 1;</code>
   * @param value The bytes for requestId to set.
   */
  private void setRequestIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    requestId_ = value.toStringUtf8();

  }

  public static final int STATE_FIELD_NUMBER = 2;
  private int state_;
  /**
   * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override
  public int getStateValue() {
    return state_;
  }
  /**
   * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
   * @return The state.
   */
  @java.lang.Override
  public com.xopmc.galaxybridge.protocol.v1.CameraCaptureState getState() {
    com.xopmc.galaxybridge.protocol.v1.CameraCaptureState result = com.xopmc.galaxybridge.protocol.v1.CameraCaptureState.forNumber(state_);
    return result == null ? com.xopmc.galaxybridge.protocol.v1.CameraCaptureState.UNRECOGNIZED : result;
  }
  /**
   * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
   * @param value The enum numeric value on the wire for state to set.
   */
  private void setStateValue(int value) {
      state_ = value;
  }
  /**
   * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
   * @param value The state to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setState(com.xopmc.galaxybridge.protocol.v1.CameraCaptureState value) {
    state_ = value.getNumber();

  }
  /**
   * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
   */
  private void clearState() {

    state_ = 0;
  }

  public static final int REASON_CODE_FIELD_NUMBER = 3;
  private java.lang.String reasonCode_;
  /**
   * <code>string reason_code = 3;</code>
   * @return The reasonCode.
   */
  @java.lang.Override
  public java.lang.String getReasonCode() {
    return reasonCode_;
  }
  /**
   * <code>string reason_code = 3;</code>
   * @return The bytes for reasonCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonCodeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reasonCode_);
  }
  /**
   * <code>string reason_code = 3;</code>
   * @param value The reasonCode to set.
   */
  private void setReasonCode(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    reasonCode_ = value;
  }
  /**
   * <code>string reason_code = 3;</code>
   */
  private void clearReasonCode() {

    reasonCode_ = getDefaultInstance().getReasonCode();
  }
  /**
   * <code>string reason_code = 3;</code>
   * @param value The bytes for reasonCode to set.
   */
  private void setReasonCodeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reasonCode_ = value.toStringUtf8();

  }

  public static final int RETRYABLE_FIELD_NUMBER = 4;
  private boolean retryable_;
  /**
   * <code>bool retryable = 4;</code>
   * @return The retryable.
   */
  @java.lang.Override
  public boolean getRetryable() {
    return retryable_;
  }
  /**
   * <code>bool retryable = 4;</code>
   * @param value The retryable to set.
   */
  private void setRetryable(boolean value) {
    
    retryable_ = value;
  }
  /**
   * <code>bool retryable = 4;</code>
   */
  private void clearRetryable() {

    retryable_ = false;
  }

  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.CameraStatus prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.CameraStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.CameraStatus, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.CameraStatus)
      com.xopmc.galaxybridge.protocol.v1.CameraStatusOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.CameraStatus.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      return instance.getRequestId();
    }
    /**
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      return instance.getRequestIdBytes();
    }
    /**
     * <code>string request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRequestId(value);
      return this;
    }
    /**
     * <code>string request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      copyOnWrite();
      instance.clearRequestId();
      return this;
    }
    /**
     * <code>string request_id = 1;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRequestIdBytes(value);
      return this;
    }

    /**
     * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override
    public int getStateValue() {
      return instance.getStateValue();
    }
    /**
     * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
     * @param value The state to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      copyOnWrite();
      instance.setStateValue(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
     * @return The state.
     */
    @java.lang.Override
    public com.xopmc.galaxybridge.protocol.v1.CameraCaptureState getState() {
      return instance.getState();
    }
    /**
     * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setState(com.xopmc.galaxybridge.protocol.v1.CameraCaptureState value) {
      copyOnWrite();
      instance.setState(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.CameraCaptureState state = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }

    /**
     * <code>string reason_code = 3;</code>
     * @return The reasonCode.
     */
    @java.lang.Override
    public java.lang.String getReasonCode() {
      return instance.getReasonCode();
    }
    /**
     * <code>string reason_code = 3;</code>
     * @return The bytes for reasonCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonCodeBytes() {
      return instance.getReasonCodeBytes();
    }
    /**
     * <code>string reason_code = 3;</code>
     * @param value The reasonCode to set.
     * @return This builder for chaining.
     */
    public Builder setReasonCode(
        java.lang.String value) {
      copyOnWrite();
      instance.setReasonCode(value);
      return this;
    }
    /**
     * <code>string reason_code = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReasonCode() {
      copyOnWrite();
      instance.clearReasonCode();
      return this;
    }
    /**
     * <code>string reason_code = 3;</code>
     * @param value The bytes for reasonCode to set.
     * @return This builder for chaining.
     */
    public Builder setReasonCodeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReasonCodeBytes(value);
      return this;
    }

    /**
     * <code>bool retryable = 4;</code>
     * @return The retryable.
     */
    @java.lang.Override
    public boolean getRetryable() {
      return instance.getRetryable();
    }
    /**
     * <code>bool retryable = 4;</code>
     * @param value The retryable to set.
     * @return This builder for chaining.
     */
    public Builder setRetryable(boolean value) {
      copyOnWrite();
      instance.setRetryable(value);
      return this;
    }
    /**
     * <code>bool retryable = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRetryable() {
      copyOnWrite();
      instance.clearRetryable();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.CameraStatus)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.CameraStatus();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "requestId_",
            "state_",
            "reasonCode_",
            "retryable_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\f" +
              "\u0003\u0208\u0004\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.CameraStatus> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.CameraStatus.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.CameraStatus>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.CameraStatus)
  private static final com.xopmc.galaxybridge.protocol.v1.CameraStatus DEFAULT_INSTANCE;
  static {
    CameraStatus defaultInstance = new CameraStatus();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CameraStatus.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.CameraStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CameraStatus> PARSER;

  public static com.google.protobuf.Parser<CameraStatus> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

