// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface CapabilityUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.CapabilityUpdate)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
   * @return The enum numeric value on the wire for transport.
   */
  int getTransportValue();
  /**
   * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
   * @return The transport.
   */
  com.xopmc.galaxybridge.protocol.v1.TransportKind getTransport();

  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @return A list containing the available.
   */
  java.util.List<com.xopmc.galaxybridge.protocol.v1.Capability> getAvailableList();
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @return The count of available.
   */
  int getAvailableCount();
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @param index The index of the element to return.
   * @return The available at the given index.
   */
  com.xopmc.galaxybridge.protocol.v1.Capability getAvailable(int index);
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @return A list containing the enum numeric values on the wire for available.
   */
  java.util.List<java.lang.Integer>
  getAvailableValueList();
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of available at the given index.
   */
  int getAvailableValue(int index);

  /**
   * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
   */
  int getUnavailableReasonsCount();
  /**
   * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
   */
  boolean containsUnavailableReasons(
      java.lang.String key);
  /**
   * Use {@link #getUnavailableReasonsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getUnavailableReasons();
  /**
   * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getUnavailableReasonsMap();
  /**
   * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
   */

  /* nullable */
java.lang.String getUnavailableReasonsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
   */

  java.lang.String getUnavailableReasonsOrThrow(
      java.lang.String key);
}
