// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.CapabilityUpdate}
 */
@com.google.protobuf.Generated
public  final class CapabilityUpdate extends
    com.google.protobuf.GeneratedMessageLite<
        CapabilityUpdate, CapabilityUpdate.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.CapabilityUpdate)
    CapabilityUpdateOrBuilder {
  private CapabilityUpdate() {
    available_ = emptyIntList();
  }
  public static final int TRANSPORT_FIELD_NUMBER = 1;
  private int transport_;
  /**
   * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
   * @return The enum numeric value on the wire for transport.
   */
  @java.lang.Override
  public int getTransportValue() {
    return transport_;
  }
  /**
   * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
   * @return The transport.
   */
  @java.lang.Override
  public com.xopmc.galaxybridge.protocol.v1.TransportKind getTransport() {
    com.xopmc.galaxybridge.protocol.v1.TransportKind result = com.xopmc.galaxybridge.protocol.v1.TransportKind.forNumber(transport_);
    return result == null ? com.xopmc.galaxybridge.protocol.v1.TransportKind.UNRECOGNIZED : result;
  }
  /**
   * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
   * @param value The enum numeric value on the wire for transport to set.
   */
  private void setTransportValue(int value) {
      transport_ = value;
  }
  /**
   * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
   * @param value The transport to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setTransport(com.xopmc.galaxybridge.protocol.v1.TransportKind value) {
    transport_ = value.getNumber();

  }
  /**
   * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
   */
  private void clearTransport() {

    transport_ = 0;
  }

  public static final int AVAILABLE_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.IntList available_;
  private static final com.google.protobuf.Internal.IntListAdapter.IntConverter<
      com.xopmc.galaxybridge.protocol.v1.Capability> available_converter_ =
          new com.google.protobuf.Internal.IntListAdapter.IntConverter<
              com.xopmc.galaxybridge.protocol.v1.Capability>() {
            @java.lang.Override
            public com.xopmc.galaxybridge.protocol.v1.Capability convert(int from) {
              com.xopmc.galaxybridge.protocol.v1.Capability result = com.xopmc.galaxybridge.protocol.v1.Capability.forNumber(from);
              return result == null ? com.xopmc.galaxybridge.protocol.v1.Capability.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @return A list containing the available.
   */
  @java.lang.Override
  public java.util.List<com.xopmc.galaxybridge.protocol.v1.Capability> getAvailableList() {
    return new com.google.protobuf.Internal.IntListAdapter<
        com.xopmc.galaxybridge.protocol.v1.Capability>(available_, available_converter_);
  }
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @return The count of available.
   */
  @java.lang.Override
  public int getAvailableCount() {
    return available_.size();
  }
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @param index The index of the element to return.
   * @return The available at the given index.
   */
  @java.lang.Override
  public com.xopmc.galaxybridge.protocol.v1.Capability getAvailable(int index) {
    com.xopmc.galaxybridge.protocol.v1.Capability result = com.xopmc.galaxybridge.protocol.v1.Capability.forNumber(available_.getInt(index));
    return result == null ? com.xopmc.galaxybridge.protocol.v1.Capability.UNRECOGNIZED : result;
  }
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @return A list containing the enum numeric values on the wire for available.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getAvailableValueList() {
    return available_;
  }
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of available at the given index.
   */
  @java.lang.Override
  public int getAvailableValue(int index) {
    return available_.getInt(index);
  }
  private int availableMemoizedSerializedSize;
  private void ensureAvailableIsMutable() {
    com.google.protobuf.Internal.IntList tmp = available_;
    if (!tmp.isModifiable()) {
      available_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
    }
  }
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @param index The index to set the value at.
   * @param value The available to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setAvailable(
      int index, com.xopmc.galaxybridge.protocol.v1.Capability value) {
    java.util.Objects.requireNonNull(value);
    ensureAvailableIsMutable();
    available_.setInt(index, value.getNumber());
  }
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @param value The available to add.
   */
  private void addAvailable(com.xopmc.galaxybridge.protocol.v1.Capability value) {
    java.util.Objects.requireNonNull(value);
    ensureAvailableIsMutable();
    available_.addInt(value.getNumber());
  }
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @param values The available to add.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void addAllAvailable(
      java.lang.Iterable<? extends com.xopmc.galaxybridge.protocol.v1.Capability> values) {
    ensureAvailableIsMutable();
    for (com.xopmc.galaxybridge.protocol.v1.Capability value : values) {
      available_.addInt(value.getNumber());
    }
  }
  /**
   * `repeated .galaxybridge.v1.Capability available = 2;`
   */
  private void clearAvailable() {
    available_ = emptyIntList();
  }
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @param value The enum numeric value on the wire for available to set.
   */
  private void setAvailableValue(
      int index, int value) {
    ensureAvailableIsMutable();
    available_.setInt(index, value);
  }
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @param value The enum numeric value on the wire for available to add.
   */
  private void addAvailableValue(int value) {
    ensureAvailableIsMutable();
    available_.addInt(value);
  }
  /**
   * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
   * @param values The enum numeric values on the wire for available to add.
   */
  private void addAllAvailableValue(
      java.lang.Iterable<java.lang.Integer> values) {
    ensureAvailableIsMutable();
    for (int value : values) {
      available_.addInt(value);
    }
  }

  public static final int UNAVAILABLE_REASONS_FIELD_NUMBER = 3;
  private static final class UnavailableReasonsDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.String> unavailableReasons_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetUnavailableReasons() {
    return unavailableReasons_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetMutableUnavailableReasons() {
    if (!unavailableReasons_.isMutable()) {
      unavailableReasons_ = unavailableReasons_.mutableCopy();
    }
    return unavailableReasons_;
  }
  @java.lang.Override

  public int getUnavailableReasonsCount() {
    return internalGetUnavailableReasons().size();
  }
  /**
   * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
   */
  @java.lang.Override

  public boolean containsUnavailableReasons(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key);
    return internalGetUnavailableReasons().containsKey(key);
  }
  /**
   * Use {@link #getUnavailableReasonsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getUnavailableReasons() {
    return getUnavailableReasonsMap();
  }
  /**
   * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getUnavailableReasonsMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetUnavailableReasons());
  }
  /**
   * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
   */
  @java.lang.Override

  public /* nullable */
java.lang.String getUnavailableReasonsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    java.util.Objects.requireNonNull(key);
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetUnavailableReasons();
    java.lang.String v = map.get(key);
    return v != null ? v : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
   */
  @java.lang.Override

  public java.lang.String getUnavailableReasonsOrThrow(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key);
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetUnavailableReasons();
    java.lang.String v = map.get(key);
    if (v == null) {
      throw new java.lang.IllegalArgumentException();
    }
    return v;
  }
  /**
   * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
   */
  private java.util.Map<java.lang.String, java.lang.String>
  getMutableUnavailableReasonsMap() {
    return internalGetMutableUnavailableReasons();
  }

  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.CapabilityUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.CapabilityUpdate)
      com.xopmc.galaxybridge.protocol.v1.CapabilityUpdateOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
     * @return The enum numeric value on the wire for transport.
     */
    @java.lang.Override
    public int getTransportValue() {
      return instance.getTransportValue();
    }
    /**
     * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
     * @param value The transport to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setTransportValue(int value) {
      copyOnWrite();
      instance.setTransportValue(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
     * @return The transport.
     */
    @java.lang.Override
    public com.xopmc.galaxybridge.protocol.v1.TransportKind getTransport() {
      return instance.getTransport();
    }
    /**
     * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
     * @param value The enum numeric value on the wire for transport to set.
     * @return This builder for chaining.
     */
    public Builder setTransport(com.xopmc.galaxybridge.protocol.v1.TransportKind value) {
      copyOnWrite();
      instance.setTransport(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.TransportKind transport = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransport() {
      copyOnWrite();
      instance.clearTransport();
      return this;
    }

    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @return A list containing the available.
     */
    @java.lang.Override
    public java.util.List<com.xopmc.galaxybridge.protocol.v1.Capability> getAvailableList() {
      return instance.getAvailableList();
    }
    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @return The count of available.
     */
    @java.lang.Override
    public int getAvailableCount() {
      return instance.getAvailableCount();
    }
    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @param index The index of the element to return.
     * @return The available at the given index.
     */
    @java.lang.Override
    public com.xopmc.galaxybridge.protocol.v1.Capability getAvailable(int index) {
      return instance.getAvailable(index);
    }
    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @param index The index to set the value at.
     * @param value The available to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setAvailable(
        int index, com.xopmc.galaxybridge.protocol.v1.Capability value) {
      copyOnWrite();
      instance.setAvailable(index, value);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @param value The available to add.
     * @return This builder for chaining.
     */
    public Builder addAvailable(com.xopmc.galaxybridge.protocol.v1.Capability value) {
      copyOnWrite();
      instance.addAvailable(value);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @param values The available to add.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder addAllAvailable(
        java.lang.Iterable<? extends com.xopmc.galaxybridge.protocol.v1.Capability> values) {
      copyOnWrite();
      instance.addAllAvailable(values);  return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailable() {
      copyOnWrite();
      instance.clearAvailable();
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @return A list containing the enum numeric values on the wire for available.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getAvailableValueList() {
      return java.util.Collections.unmodifiableList(
          instance.getAvailableValueList());
    }
    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of available at the given index.
     */
    @java.lang.Override
    public int getAvailableValue(int index) {
      return instance.getAvailableValue(index);
    }
    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for available to set.
     * @return This builder for chaining.
     */
    public Builder setAvailableValue(
        int index, int value) {
      copyOnWrite();
      instance.setAvailableValue(index, value);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @param value The enum numeric value on the wire for available to add.
     * @return This builder for chaining.
     */
    public Builder addAvailableValue(int value) {
      copyOnWrite();
      instance.addAvailableValue(value);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.Capability available = 2;</code>
     * @param values The enum numeric values on the wire for available to add.
     * @return This builder for chaining.
     */
    public Builder addAllAvailableValue(
        java.lang.Iterable<java.lang.Integer> values) {
      copyOnWrite();
      instance.addAllAvailableValue(values);
      return this;
    }

    @java.lang.Override

    public int getUnavailableReasonsCount() {
      return instance.getUnavailableReasonsMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
     */
    @java.lang.Override

    public boolean containsUnavailableReasons(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      return instance.getUnavailableReasonsMap().containsKey(key);
    }

    public Builder clearUnavailableReasons() {
      copyOnWrite();
      instance.getMutableUnavailableReasonsMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
     */

    public Builder removeUnavailableReasons(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      copyOnWrite();
      instance.getMutableUnavailableReasonsMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getUnavailableReasonsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getUnavailableReasons() {
      return getUnavailableReasonsMap();
    }
    /**
     * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getUnavailableReasonsMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getUnavailableReasonsMap());
    }
    /**
     * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
     */
    @java.lang.Override

    public /* nullable */
java.lang.String getUnavailableReasonsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      java.util.Objects.requireNonNull(key);
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getUnavailableReasonsMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getUnavailableReasonsOrThrow(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getUnavailableReasonsMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
     */
    public Builder putUnavailableReasons(
        java.lang.String key,
        java.lang.String value) {
      java.util.Objects.requireNonNull(key);
      java.util.Objects.requireNonNull(value);
      copyOnWrite();
      instance.getMutableUnavailableReasonsMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; unavailable_reasons = 3;</code>
     */
    public Builder putAllUnavailableReasons(
        java.util.Map<java.lang.String, java.lang.String> values) {
      copyOnWrite();
      instance.getMutableUnavailableReasonsMap().putAll(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.CapabilityUpdate)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "transport_",
            "available_",
            "unavailableReasons_",
            UnavailableReasonsDefaultEntryHolder.defaultEntry,
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0001\u0001\u0000\u0001\f\u0002,\u0003" +
              "2";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.CapabilityUpdate)
  private static final com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate DEFAULT_INSTANCE;
  static {
    CapabilityUpdate defaultInstance = new CapabilityUpdate();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CapabilityUpdate.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CapabilityUpdate> PARSER;

  public static com.google.protobuf.Parser<CapabilityUpdate> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

