// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf enum {@code galaxybridge.v1.ClipboardKind}
 */
@com.google.protobuf.Generated
public enum ClipboardKind
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>CLIPBOARD_KIND_UNSPECIFIED = 0;</code>
   */
  CLIPBOARD_KIND_UNSPECIFIED(0),
  /**
   * <code>CLIPBOARD_KIND_TEXT = 1;</code>
   */
  CLIPBOARD_KIND_TEXT(1),
  /**
   * <code>CLIPBOARD_KIND_URL = 2;</code>
   */
  CLIPBOARD_KIND_URL(2),
  /**
   * <code>CLIPBOARD_KIND_PNG = 3;</code>
   */
  CLIPBOARD_KIND_PNG(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CLIPBOARD_KIND_UNSPECIFIED = 0;</code>
   */
  public static final int CLIPBOARD_KIND_UNSPECIFIED_VALUE = 0;
  /**
   * <code>CLIPBOARD_KIND_TEXT = 1;</code>
   */
  public static final int CLIPBOARD_KIND_TEXT_VALUE = 1;
  /**
   * <code>CLIPBOARD_KIND_URL = 2;</code>
   */
  public static final int CLIPBOARD_KIND_URL_VALUE = 2;
  /**
   * <code>CLIPBOARD_KIND_PNG = 3;</code>
   */
  public static final int CLIPBOARD_KIND_PNG_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ClipboardKind valueOf(int value) {
    return forNumber(value);
  }

  public static ClipboardKind forNumber(int value) {
    switch (value) {
      case 0: return CLIPBOARD_KIND_UNSPECIFIED;
      case 1: return CLIPBOARD_KIND_TEXT;
      case 2: return CLIPBOARD_KIND_URL;
      case 3: return CLIPBOARD_KIND_PNG;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ClipboardKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ClipboardKind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ClipboardKind>() {
          @java.lang.Override
          public ClipboardKind findValueByNumber(int number) {
            return ClipboardKind.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return ClipboardKindVerifier.INSTANCE;
  }

  private static final class ClipboardKindVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new ClipboardKindVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return ClipboardKind.forNumber(number) != null;
          }
        };

  private final int value;

  private ClipboardKind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:galaxybridge.v1.ClipboardKind)
}

