// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.ClipboardUpdate}
 */
@com.google.protobuf.Generated
public  final class ClipboardUpdate extends
    com.google.protobuf.GeneratedMessageLite<
        ClipboardUpdate, ClipboardUpdate.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.ClipboardUpdate)
    ClipboardUpdateOrBuilder {
  private ClipboardUpdate() {
    changeId_ = "";
    content_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int CHANGE_ID_FIELD_NUMBER = 1;
  private java.lang.String changeId_;
  /**
   * <code>string change_id = 1;</code>
   * @return The changeId.
   */
  @java.lang.Override
  public java.lang.String getChangeId() {
    return changeId_;
  }
  /**
   * <code>string change_id = 1;</code>
   * @return The bytes for changeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChangeIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(changeId_);
  }
  /**
   * <code>string change_id = 1;</code>
   * @param value The changeId to set.
   */
  private void setChangeId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    changeId_ = value;
  }
  /**
   * <code>string change_id = 1;</code>
   */
  private void clearChangeId() {

    changeId_ = getDefaultInstance().getChangeId();
  }
  /**
   * <code>string change_id = 1;</code>
   * @param value The bytes for changeId to set.
   */
  private void setChangeIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    changeId_ = value.toStringUtf8();

  }

  public static final int KIND_FIELD_NUMBER = 2;
  private int kind_;
  /**
   * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
   * @return The enum numeric value on the wire for kind.
   */
  @java.lang.Override
  public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
   * @return The kind.
   */
  @java.lang.Override
  public com.xopmc.galaxybridge.protocol.v1.ClipboardKind getKind() {
    com.xopmc.galaxybridge.protocol.v1.ClipboardKind result = com.xopmc.galaxybridge.protocol.v1.ClipboardKind.forNumber(kind_);
    return result == null ? com.xopmc.galaxybridge.protocol.v1.ClipboardKind.UNRECOGNIZED : result;
  }
  /**
   * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
   * @param value The enum numeric value on the wire for kind to set.
   */
  private void setKindValue(int value) {
      kind_ = value;
  }
  /**
   * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
   * @param value The kind to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setKind(com.xopmc.galaxybridge.protocol.v1.ClipboardKind value) {
    kind_ = value.getNumber();

  }
  /**
   * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
   */
  private void clearKind() {

    kind_ = 0;
  }

  public static final int CONTENT_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString content_;
  /**
   * <code>bytes content = 3;</code>
   * @return The content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getContent() {
    return content_;
  }
  /**
   * <code>bytes content = 3;</code>
   * @param value The content to set.
   */
  private void setContent(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    content_ = value;
  }
  /**
   * <code>bytes content = 3;</code>
   */
  private void clearContent() {

    content_ = getDefaultInstance().getContent();
  }

  public static final int SENSITIVE_FIELD_NUMBER = 4;
  private boolean sensitive_;
  /**
   * <code>bool sensitive = 4;</code>
   * @return The sensitive.
   */
  @java.lang.Override
  public boolean getSensitive() {
    return sensitive_;
  }
  /**
   * <code>bool sensitive = 4;</code>
   * @param value The sensitive to set.
   */
  private void setSensitive(boolean value) {
    
    sensitive_ = value;
  }
  /**
   * <code>bool sensitive = 4;</code>
   */
  private void clearSensitive() {

    sensitive_ = false;
  }

  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.ClipboardUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.ClipboardUpdate)
      com.xopmc.galaxybridge.protocol.v1.ClipboardUpdateOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string change_id = 1;</code>
     * @return The changeId.
     */
    @java.lang.Override
    public java.lang.String getChangeId() {
      return instance.getChangeId();
    }
    /**
     * <code>string change_id = 1;</code>
     * @return The bytes for changeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChangeIdBytes() {
      return instance.getChangeIdBytes();
    }
    /**
     * <code>string change_id = 1;</code>
     * @param value The changeId to set.
     * @return This builder for chaining.
     */
    public Builder setChangeId(
        java.lang.String value) {
      copyOnWrite();
      instance.setChangeId(value);
      return this;
    }
    /**
     * <code>string change_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChangeId() {
      copyOnWrite();
      instance.clearChangeId();
      return this;
    }
    /**
     * <code>string change_id = 1;</code>
     * @param value The bytes for changeId to set.
     * @return This builder for chaining.
     */
    public Builder setChangeIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setChangeIdBytes(value);
      return this;
    }

    /**
     * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override
    public int getKindValue() {
      return instance.getKindValue();
    }
    /**
     * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
     * @param value The kind to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setKindValue(int value) {
      copyOnWrite();
      instance.setKindValue(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
     * @return The kind.
     */
    @java.lang.Override
    public com.xopmc.galaxybridge.protocol.v1.ClipboardKind getKind() {
      return instance.getKind();
    }
    /**
     * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
     * @param value The enum numeric value on the wire for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(com.xopmc.galaxybridge.protocol.v1.ClipboardKind value) {
      copyOnWrite();
      instance.setKind(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      copyOnWrite();
      instance.clearKind();
      return this;
    }

    /**
     * <code>bytes content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContent() {
      return instance.getContent();
    }
    /**
     * <code>bytes content = 3;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setContent(value);
      return this;
    }
    /**
     * <code>bytes content = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      copyOnWrite();
      instance.clearContent();
      return this;
    }

    /**
     * <code>bool sensitive = 4;</code>
     * @return The sensitive.
     */
    @java.lang.Override
    public boolean getSensitive() {
      return instance.getSensitive();
    }
    /**
     * <code>bool sensitive = 4;</code>
     * @param value The sensitive to set.
     * @return This builder for chaining.
     */
    public Builder setSensitive(boolean value) {
      copyOnWrite();
      instance.setSensitive(value);
      return this;
    }
    /**
     * <code>bool sensitive = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensitive() {
      copyOnWrite();
      instance.clearSensitive();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.ClipboardUpdate)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "changeId_",
            "kind_",
            "content_",
            "sensitive_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\f" +
              "\u0003\n\u0004\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.ClipboardUpdate)
  private static final com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate DEFAULT_INSTANCE;
  static {
    ClipboardUpdate defaultInstance = new ClipboardUpdate();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ClipboardUpdate.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ClipboardUpdate> PARSER;

  public static com.google.protobuf.Parser<ClipboardUpdate> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

