// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface ClipboardUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.ClipboardUpdate)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string change_id = 1;</code>
   * @return The changeId.
   */
  java.lang.String getChangeId();
  /**
   * <code>string change_id = 1;</code>
   * @return The bytes for changeId.
   */
  com.google.protobuf.ByteString
      getChangeIdBytes();

  /**
   * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.galaxybridge.v1.ClipboardKind kind = 2;</code>
   * @return The kind.
   */
  com.xopmc.galaxybridge.protocol.v1.ClipboardKind getKind();

  /**
   * <code>bytes content = 3;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>bool sensitive = 4;</code>
   * @return The sensitive.
   */
  boolean getSensitive();
}
