// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface EnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.Envelope)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 protocol_major = 1;</code>
   * @return The protocolMajor.
   */
  int getProtocolMajor();

  /**
   * <code>uint32 protocol_minor = 2;</code>
   * @return The protocolMinor.
   */
  int getProtocolMinor();

  /**
   * <code>string device_id = 3;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 3;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string session_id = 4;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 4;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>uint64 message_id = 5;</code>
   * @return The messageId.
   */
  long getMessageId();

  /**
   * <code>.galaxybridge.v1.Hello hello = 10;</code>
   * @return Whether the hello field is set.
   */
  boolean hasHello();
  /**
   * <code>.galaxybridge.v1.Hello hello = 10;</code>
   * @return The hello.
   */
  com.xopmc.galaxybridge.protocol.v1.Hello getHello();

  /**
   * <code>.galaxybridge.v1.PairingRequest pairing_request = 11;</code>
   * @return Whether the pairingRequest field is set.
   */
  boolean hasPairingRequest();
  /**
   * <code>.galaxybridge.v1.PairingRequest pairing_request = 11;</code>
   * @return The pairingRequest.
   */
  com.xopmc.galaxybridge.protocol.v1.PairingRequest getPairingRequest();

  /**
   * <code>.galaxybridge.v1.PairingResponse pairing_response = 12;</code>
   * @return Whether the pairingResponse field is set.
   */
  boolean hasPairingResponse();
  /**
   * <code>.galaxybridge.v1.PairingResponse pairing_response = 12;</code>
   * @return The pairingResponse.
   */
  com.xopmc.galaxybridge.protocol.v1.PairingResponse getPairingResponse();

  /**
   * <code>.galaxybridge.v1.CapabilityUpdate capability_update = 13;</code>
   * @return Whether the capabilityUpdate field is set.
   */
  boolean hasCapabilityUpdate();
  /**
   * <code>.galaxybridge.v1.CapabilityUpdate capability_update = 13;</code>
   * @return The capabilityUpdate.
   */
  com.xopmc.galaxybridge.protocol.v1.CapabilityUpdate getCapabilityUpdate();

  /**
   * <code>.galaxybridge.v1.OpenChannel open_channel = 14;</code>
   * @return Whether the openChannel field is set.
   */
  boolean hasOpenChannel();
  /**
   * <code>.galaxybridge.v1.OpenChannel open_channel = 14;</code>
   * @return The openChannel.
   */
  com.xopmc.galaxybridge.protocol.v1.OpenChannel getOpenChannel();

  /**
   * <code>.galaxybridge.v1.InputEvent input_event = 15;</code>
   * @return Whether the inputEvent field is set.
   */
  boolean hasInputEvent();
  /**
   * <code>.galaxybridge.v1.InputEvent input_event = 15;</code>
   * @return The inputEvent.
   */
  com.xopmc.galaxybridge.protocol.v1.InputEvent getInputEvent();

  /**
   * <code>.galaxybridge.v1.ClipboardUpdate clipboard_update = 16;</code>
   * @return Whether the clipboardUpdate field is set.
   */
  boolean hasClipboardUpdate();
  /**
   * <code>.galaxybridge.v1.ClipboardUpdate clipboard_update = 16;</code>
   * @return The clipboardUpdate.
   */
  com.xopmc.galaxybridge.protocol.v1.ClipboardUpdate getClipboardUpdate();

  /**
   * <code>.galaxybridge.v1.NotificationEvent notification_event = 17;</code>
   * @return Whether the notificationEvent field is set.
   */
  boolean hasNotificationEvent();
  /**
   * <code>.galaxybridge.v1.NotificationEvent notification_event = 17;</code>
   * @return The notificationEvent.
   */
  com.xopmc.galaxybridge.protocol.v1.NotificationEvent getNotificationEvent();

  /**
   * <code>.galaxybridge.v1.NotificationAction notification_action = 18;</code>
   * @return Whether the notificationAction field is set.
   */
  boolean hasNotificationAction();
  /**
   * <code>.galaxybridge.v1.NotificationAction notification_action = 18;</code>
   * @return The notificationAction.
   */
  com.xopmc.galaxybridge.protocol.v1.NotificationAction getNotificationAction();

  /**
   * <code>.galaxybridge.v1.TransferManifest transfer_manifest = 19;</code>
   * @return Whether the transferManifest field is set.
   */
  boolean hasTransferManifest();
  /**
   * <code>.galaxybridge.v1.TransferManifest transfer_manifest = 19;</code>
   * @return The transferManifest.
   */
  com.xopmc.galaxybridge.protocol.v1.TransferManifest getTransferManifest();

  /**
   * <code>.galaxybridge.v1.TransferChunk transfer_chunk = 20;</code>
   * @return Whether the transferChunk field is set.
   */
  boolean hasTransferChunk();
  /**
   * <code>.galaxybridge.v1.TransferChunk transfer_chunk = 20;</code>
   * @return The transferChunk.
   */
  com.xopmc.galaxybridge.protocol.v1.TransferChunk getTransferChunk();

  /**
   * <code>.galaxybridge.v1.TransferAck transfer_ack = 21;</code>
   * @return Whether the transferAck field is set.
   */
  boolean hasTransferAck();
  /**
   * <code>.galaxybridge.v1.TransferAck transfer_ack = 21;</code>
   * @return The transferAck.
   */
  com.xopmc.galaxybridge.protocol.v1.TransferAck getTransferAck();

  /**
   * <code>.galaxybridge.v1.SmsEvent sms_event = 22;</code>
   * @return Whether the smsEvent field is set.
   */
  boolean hasSmsEvent();
  /**
   * <code>.galaxybridge.v1.SmsEvent sms_event = 22;</code>
   * @return The smsEvent.
   */
  com.xopmc.galaxybridge.protocol.v1.SmsEvent getSmsEvent();

  /**
   * <code>.galaxybridge.v1.CallEvent call_event = 23;</code>
   * @return Whether the callEvent field is set.
   */
  boolean hasCallEvent();
  /**
   * <code>.galaxybridge.v1.CallEvent call_event = 23;</code>
   * @return The callEvent.
   */
  com.xopmc.galaxybridge.protocol.v1.CallEvent getCallEvent();

  /**
   * <code>.galaxybridge.v1.CameraConfiguration camera_configuration = 24;</code>
   * @return Whether the cameraConfiguration field is set.
   */
  boolean hasCameraConfiguration();
  /**
   * <code>.galaxybridge.v1.CameraConfiguration camera_configuration = 24;</code>
   * @return The cameraConfiguration.
   */
  com.xopmc.galaxybridge.protocol.v1.CameraConfiguration getCameraConfiguration();

  /**
   * <code>.galaxybridge.v1.ErrorEvent error = 25;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.galaxybridge.v1.ErrorEvent error = 25;</code>
   * @return The error.
   */
  com.xopmc.galaxybridge.protocol.v1.ErrorEvent getError();

  /**
   * <code>.galaxybridge.v1.Ping ping = 26;</code>
   * @return Whether the ping field is set.
   */
  boolean hasPing();
  /**
   * <code>.galaxybridge.v1.Ping ping = 26;</code>
   * @return The ping.
   */
  com.xopmc.galaxybridge.protocol.v1.Ping getPing();

  /**
   * <code>.galaxybridge.v1.Pong pong = 27;</code>
   * @return Whether the pong field is set.
   */
  boolean hasPong();
  /**
   * <code>.galaxybridge.v1.Pong pong = 27;</code>
   * @return The pong.
   */
  com.xopmc.galaxybridge.protocol.v1.Pong getPong();

  /**
   * <code>.galaxybridge.v1.AdbBindingRequest adb_binding_request = 28;</code>
   * @return Whether the adbBindingRequest field is set.
   */
  boolean hasAdbBindingRequest();
  /**
   * <code>.galaxybridge.v1.AdbBindingRequest adb_binding_request = 28;</code>
   * @return The adbBindingRequest.
   */
  com.xopmc.galaxybridge.protocol.v1.AdbBindingRequest getAdbBindingRequest();

  /**
   * <code>.galaxybridge.v1.AdbBindingResponse adb_binding_response = 29;</code>
   * @return Whether the adbBindingResponse field is set.
   */
  boolean hasAdbBindingResponse();
  /**
   * <code>.galaxybridge.v1.AdbBindingResponse adb_binding_response = 29;</code>
   * @return The adbBindingResponse.
   */
  com.xopmc.galaxybridge.protocol.v1.AdbBindingResponse getAdbBindingResponse();

  /**
   * <code>.galaxybridge.v1.SessionAuthentication session_authentication = 30;</code>
   * @return Whether the sessionAuthentication field is set.
   */
  boolean hasSessionAuthentication();
  /**
   * <code>.galaxybridge.v1.SessionAuthentication session_authentication = 30;</code>
   * @return The sessionAuthentication.
   */
  com.xopmc.galaxybridge.protocol.v1.SessionAuthentication getSessionAuthentication();

  /**
   * <code>.galaxybridge.v1.PairingCommit pairing_commit = 31;</code>
   * @return Whether the pairingCommit field is set.
   */
  boolean hasPairingCommit();
  /**
   * <code>.galaxybridge.v1.PairingCommit pairing_commit = 31;</code>
   * @return The pairingCommit.
   */
  com.xopmc.galaxybridge.protocol.v1.PairingCommit getPairingCommit();

  /**
   * <code>.galaxybridge.v1.PairingCommitAck pairing_commit_ack = 32;</code>
   * @return Whether the pairingCommitAck field is set.
   */
  boolean hasPairingCommitAck();
  /**
   * <code>.galaxybridge.v1.PairingCommitAck pairing_commit_ack = 32;</code>
   * @return The pairingCommitAck.
   */
  com.xopmc.galaxybridge.protocol.v1.PairingCommitAck getPairingCommitAck();

  /**
   * <code>.galaxybridge.v1.CameraStatus camera_status = 33;</code>
   * @return Whether the cameraStatus field is set.
   */
  boolean hasCameraStatus();
  /**
   * <code>.galaxybridge.v1.CameraStatus camera_status = 33;</code>
   * @return The cameraStatus.
   */
  com.xopmc.galaxybridge.protocol.v1.CameraStatus getCameraStatus();

  /**
   * <code>.galaxybridge.v1.TransferCancel transfer_cancel = 34;</code>
   * @return Whether the transferCancel field is set.
   */
  boolean hasTransferCancel();
  /**
   * <code>.galaxybridge.v1.TransferCancel transfer_cancel = 34;</code>
   * @return The transferCancel.
   */
  com.xopmc.galaxybridge.protocol.v1.TransferCancel getTransferCancel();

  public com.xopmc.galaxybridge.protocol.v1.Envelope.PayloadCase getPayloadCase();
}
