// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface ErrorEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.ErrorEvent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string safe_message = 2;</code>
   * @return The safeMessage.
   */
  java.lang.String getSafeMessage();
  /**
   * <code>string safe_message = 2;</code>
   * @return The bytes for safeMessage.
   */
  com.google.protobuf.ByteString
      getSafeMessageBytes();

  /**
   * <code>bool retryable = 3;</code>
   * @return The retryable.
   */
  boolean getRetryable();
}
