// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.Hello}
 */
@com.google.protobuf.Generated
public  final class Hello extends
    com.google.protobuf.GeneratedMessageLite<
        Hello, Hello.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.Hello)
    HelloOrBuilder {
  private Hello() {
    displayName_ = "";
    publicKeyFingerprint_ = com.google.protobuf.ByteString.EMPTY;
    transports_ = emptyIntList();
  }
  public static final int DISPLAY_NAME_FIELD_NUMBER = 1;
  private java.lang.String displayName_;
  /**
   * <code>string display_name = 1;</code>
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    return displayName_;
  }
  /**
   * <code>string display_name = 1;</code>
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(displayName_);
  }
  /**
   * <code>string display_name = 1;</code>
   * @param value The displayName to set.
   */
  private void setDisplayName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    displayName_ = value;
  }
  /**
   * <code>string display_name = 1;</code>
   */
  private void clearDisplayName() {

    displayName_ = getDefaultInstance().getDisplayName();
  }
  /**
   * <code>string display_name = 1;</code>
   * @param value The bytes for displayName to set.
   */
  private void setDisplayNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    displayName_ = value.toStringUtf8();

  }

  public static final int PUBLIC_KEY_FINGERPRINT_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString publicKeyFingerprint_;
  /**
   * <code>bytes public_key_fingerprint = 2;</code>
   * @return The publicKeyFingerprint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPublicKeyFingerprint() {
    return publicKeyFingerprint_;
  }
  /**
   * <code>bytes public_key_fingerprint = 2;</code>
   * @param value The publicKeyFingerprint to set.
   */
  private void setPublicKeyFingerprint(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    publicKeyFingerprint_ = value;
  }
  /**
   * <code>bytes public_key_fingerprint = 2;</code>
   */
  private void clearPublicKeyFingerprint() {

    publicKeyFingerprint_ = getDefaultInstance().getPublicKeyFingerprint();
  }

  public static final int TRANSPORTS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.IntList transports_;
  private static final com.google.protobuf.Internal.IntListAdapter.IntConverter<
      com.xopmc.galaxybridge.protocol.v1.TransportKind> transports_converter_ =
          new com.google.protobuf.Internal.IntListAdapter.IntConverter<
              com.xopmc.galaxybridge.protocol.v1.TransportKind>() {
            @java.lang.Override
            public com.xopmc.galaxybridge.protocol.v1.TransportKind convert(int from) {
              com.xopmc.galaxybridge.protocol.v1.TransportKind result = com.xopmc.galaxybridge.protocol.v1.TransportKind.forNumber(from);
              return result == null ? com.xopmc.galaxybridge.protocol.v1.TransportKind.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @return A list containing the transports.
   */
  @java.lang.Override
  public java.util.List<com.xopmc.galaxybridge.protocol.v1.TransportKind> getTransportsList() {
    return new com.google.protobuf.Internal.IntListAdapter<
        com.xopmc.galaxybridge.protocol.v1.TransportKind>(transports_, transports_converter_);
  }
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @return The count of transports.
   */
  @java.lang.Override
  public int getTransportsCount() {
    return transports_.size();
  }
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @param index The index of the element to return.
   * @return The transports at the given index.
   */
  @java.lang.Override
  public com.xopmc.galaxybridge.protocol.v1.TransportKind getTransports(int index) {
    com.xopmc.galaxybridge.protocol.v1.TransportKind result = com.xopmc.galaxybridge.protocol.v1.TransportKind.forNumber(transports_.getInt(index));
    return result == null ? com.xopmc.galaxybridge.protocol.v1.TransportKind.UNRECOGNIZED : result;
  }
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @return A list containing the enum numeric values on the wire for transports.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getTransportsValueList() {
    return transports_;
  }
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of transports at the given index.
   */
  @java.lang.Override
  public int getTransportsValue(int index) {
    return transports_.getInt(index);
  }
  private int transportsMemoizedSerializedSize;
  private void ensureTransportsIsMutable() {
    com.google.protobuf.Internal.IntList tmp = transports_;
    if (!tmp.isModifiable()) {
      transports_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
    }
  }
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @param index The index to set the value at.
   * @param value The transports to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setTransports(
      int index, com.xopmc.galaxybridge.protocol.v1.TransportKind value) {
    java.util.Objects.requireNonNull(value);
    ensureTransportsIsMutable();
    transports_.setInt(index, value.getNumber());
  }
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @param value The transports to add.
   */
  private void addTransports(com.xopmc.galaxybridge.protocol.v1.TransportKind value) {
    java.util.Objects.requireNonNull(value);
    ensureTransportsIsMutable();
    transports_.addInt(value.getNumber());
  }
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @param values The transports to add.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void addAllTransports(
      java.lang.Iterable<? extends com.xopmc.galaxybridge.protocol.v1.TransportKind> values) {
    ensureTransportsIsMutable();
    for (com.xopmc.galaxybridge.protocol.v1.TransportKind value : values) {
      transports_.addInt(value.getNumber());
    }
  }
  /**
   * `repeated .galaxybridge.v1.TransportKind transports = 3;`
   */
  private void clearTransports() {
    transports_ = emptyIntList();
  }
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @param value The enum numeric value on the wire for transports to set.
   */
  private void setTransportsValue(
      int index, int value) {
    ensureTransportsIsMutable();
    transports_.setInt(index, value);
  }
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @param value The enum numeric value on the wire for transports to add.
   */
  private void addTransportsValue(int value) {
    ensureTransportsIsMutable();
    transports_.addInt(value);
  }
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @param values The enum numeric values on the wire for transports to add.
   */
  private void addAllTransportsValue(
      java.lang.Iterable<java.lang.Integer> values) {
    ensureTransportsIsMutable();
    for (int value : values) {
      transports_.addInt(value);
    }
  }

  public static com.xopmc.galaxybridge.protocol.v1.Hello parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Hello parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Hello parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Hello parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Hello parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Hello parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Hello parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Hello parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.Hello parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.Hello parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Hello parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Hello parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.Hello prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.Hello}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.Hello, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.Hello)
      com.xopmc.galaxybridge.protocol.v1.HelloOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.Hello.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string display_name = 1;</code>
     * @return The displayName.
     */
    @java.lang.Override
    public java.lang.String getDisplayName() {
      return instance.getDisplayName();
    }
    /**
     * <code>string display_name = 1;</code>
     * @return The bytes for displayName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      return instance.getDisplayNameBytes();
    }
    /**
     * <code>string display_name = 1;</code>
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(
        java.lang.String value) {
      copyOnWrite();
      instance.setDisplayName(value);
      return this;
    }
    /**
     * <code>string display_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      copyOnWrite();
      instance.clearDisplayName();
      return this;
    }
    /**
     * <code>string display_name = 1;</code>
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDisplayNameBytes(value);
      return this;
    }

    /**
     * <code>bytes public_key_fingerprint = 2;</code>
     * @return The publicKeyFingerprint.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKeyFingerprint() {
      return instance.getPublicKeyFingerprint();
    }
    /**
     * <code>bytes public_key_fingerprint = 2;</code>
     * @param value The publicKeyFingerprint to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKeyFingerprint(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPublicKeyFingerprint(value);
      return this;
    }
    /**
     * <code>bytes public_key_fingerprint = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicKeyFingerprint() {
      copyOnWrite();
      instance.clearPublicKeyFingerprint();
      return this;
    }

    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @return A list containing the transports.
     */
    @java.lang.Override
    public java.util.List<com.xopmc.galaxybridge.protocol.v1.TransportKind> getTransportsList() {
      return instance.getTransportsList();
    }
    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @return The count of transports.
     */
    @java.lang.Override
    public int getTransportsCount() {
      return instance.getTransportsCount();
    }
    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @param index The index of the element to return.
     * @return The transports at the given index.
     */
    @java.lang.Override
    public com.xopmc.galaxybridge.protocol.v1.TransportKind getTransports(int index) {
      return instance.getTransports(index);
    }
    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @param index The index to set the value at.
     * @param value The transports to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setTransports(
        int index, com.xopmc.galaxybridge.protocol.v1.TransportKind value) {
      copyOnWrite();
      instance.setTransports(index, value);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @param value The transports to add.
     * @return This builder for chaining.
     */
    public Builder addTransports(com.xopmc.galaxybridge.protocol.v1.TransportKind value) {
      copyOnWrite();
      instance.addTransports(value);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @param values The transports to add.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder addAllTransports(
        java.lang.Iterable<? extends com.xopmc.galaxybridge.protocol.v1.TransportKind> values) {
      copyOnWrite();
      instance.addAllTransports(values);  return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransports() {
      copyOnWrite();
      instance.clearTransports();
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @return A list containing the enum numeric values on the wire for transports.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getTransportsValueList() {
      return java.util.Collections.unmodifiableList(
          instance.getTransportsValueList());
    }
    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of transports at the given index.
     */
    @java.lang.Override
    public int getTransportsValue(int index) {
      return instance.getTransportsValue(index);
    }
    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for transports to set.
     * @return This builder for chaining.
     */
    public Builder setTransportsValue(
        int index, int value) {
      copyOnWrite();
      instance.setTransportsValue(index, value);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @param value The enum numeric value on the wire for transports to add.
     * @return This builder for chaining.
     */
    public Builder addTransportsValue(int value) {
      copyOnWrite();
      instance.addTransportsValue(value);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
     * @param values The enum numeric values on the wire for transports to add.
     * @return This builder for chaining.
     */
    public Builder addAllTransportsValue(
        java.lang.Iterable<java.lang.Integer> values) {
      copyOnWrite();
      instance.addAllTransportsValue(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.Hello)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.Hello();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "displayName_",
            "publicKeyFingerprint_",
            "transports_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\n" +
              "\u0003,";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.Hello> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.Hello.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.Hello>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.Hello)
  private static final com.xopmc.galaxybridge.protocol.v1.Hello DEFAULT_INSTANCE;
  static {
    Hello defaultInstance = new Hello();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Hello.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.Hello getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Hello> PARSER;

  public static com.google.protobuf.Parser<Hello> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

