// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface HelloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.Hello)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string display_name = 1;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <code>string display_name = 1;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>bytes public_key_fingerprint = 2;</code>
   * @return The publicKeyFingerprint.
   */
  com.google.protobuf.ByteString getPublicKeyFingerprint();

  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @return A list containing the transports.
   */
  java.util.List<com.xopmc.galaxybridge.protocol.v1.TransportKind> getTransportsList();
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @return The count of transports.
   */
  int getTransportsCount();
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @param index The index of the element to return.
   * @return The transports at the given index.
   */
  com.xopmc.galaxybridge.protocol.v1.TransportKind getTransports(int index);
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @return A list containing the enum numeric values on the wire for transports.
   */
  java.util.List<java.lang.Integer>
  getTransportsValueList();
  /**
   * <code>repeated .galaxybridge.v1.TransportKind transports = 3;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of transports at the given index.
   */
  int getTransportsValue(int index);
}
