// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.InputEvent}
 */
@com.google.protobuf.Generated
public  final class InputEvent extends
    com.google.protobuf.GeneratedMessageLite<
        InputEvent, InputEvent.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.InputEvent)
    InputEventOrBuilder {
  private InputEvent() {
    text_ = "";
  }
  public static final int ACTION_FIELD_NUMBER = 1;
  private int action_;
  /**
   * <code>.galaxybridge.v1.InputAction action = 1;</code>
   * @return The enum numeric value on the wire for action.
   */
  @java.lang.Override
  public int getActionValue() {
    return action_;
  }
  /**
   * <code>.galaxybridge.v1.InputAction action = 1;</code>
   * @return The action.
   */
  @java.lang.Override
  public com.xopmc.galaxybridge.protocol.v1.InputAction getAction() {
    com.xopmc.galaxybridge.protocol.v1.InputAction result = com.xopmc.galaxybridge.protocol.v1.InputAction.forNumber(action_);
    return result == null ? com.xopmc.galaxybridge.protocol.v1.InputAction.UNRECOGNIZED : result;
  }
  /**
   * <code>.galaxybridge.v1.InputAction action = 1;</code>
   * @param value The enum numeric value on the wire for action to set.
   */
  private void setActionValue(int value) {
      action_ = value;
  }
  /**
   * <code>.galaxybridge.v1.InputAction action = 1;</code>
   * @param value The action to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setAction(com.xopmc.galaxybridge.protocol.v1.InputAction value) {
    action_ = value.getNumber();

  }
  /**
   * <code>.galaxybridge.v1.InputAction action = 1;</code>
   */
  private void clearAction() {

    action_ = 0;
  }

  public static final int DISPLAY_ID_FIELD_NUMBER = 2;
  private int displayId_;
  /**
   * <code>uint32 display_id = 2;</code>
   * @return The displayId.
   */
  @java.lang.Override
  public int getDisplayId() {
    return displayId_;
  }
  /**
   * <code>uint32 display_id = 2;</code>
   * @param value The displayId to set.
   */
  private void setDisplayId(int value) {
    
    displayId_ = value;
  }
  /**
   * <code>uint32 display_id = 2;</code>
   */
  private void clearDisplayId() {

    displayId_ = 0;
  }

  public static final int DISPLAY_EPOCH_FIELD_NUMBER = 3;
  private int displayEpoch_;
  /**
   * <code>uint32 display_epoch = 3;</code>
   * @return The displayEpoch.
   */
  @java.lang.Override
  public int getDisplayEpoch() {
    return displayEpoch_;
  }
  /**
   * <code>uint32 display_epoch = 3;</code>
   * @param value The displayEpoch to set.
   */
  private void setDisplayEpoch(int value) {
    
    displayEpoch_ = value;
  }
  /**
   * <code>uint32 display_epoch = 3;</code>
   */
  private void clearDisplayEpoch() {

    displayEpoch_ = 0;
  }

  public static final int POINTER_ID_FIELD_NUMBER = 4;
  private long pointerId_;
  /**
   * <code>uint64 pointer_id = 4;</code>
   * @return The pointerId.
   */
  @java.lang.Override
  public long getPointerId() {
    return pointerId_;
  }
  /**
   * <code>uint64 pointer_id = 4;</code>
   * @param value The pointerId to set.
   */
  private void setPointerId(long value) {
    
    pointerId_ = value;
  }
  /**
   * <code>uint64 pointer_id = 4;</code>
   */
  private void clearPointerId() {

    pointerId_ = 0L;
  }

  public static final int NORMALIZED_X_FIELD_NUMBER = 5;
  private float normalizedX_;
  /**
   * <code>float normalized_x = 5;</code>
   * @return The normalizedX.
   */
  @java.lang.Override
  public float getNormalizedX() {
    return normalizedX_;
  }
  /**
   * <code>float normalized_x = 5;</code>
   * @param value The normalizedX to set.
   */
  private void setNormalizedX(float value) {
    
    normalizedX_ = value;
  }
  /**
   * <code>float normalized_x = 5;</code>
   */
  private void clearNormalizedX() {

    normalizedX_ = 0F;
  }

  public static final int NORMALIZED_Y_FIELD_NUMBER = 6;
  private float normalizedY_;
  /**
   * <code>float normalized_y = 6;</code>
   * @return The normalizedY.
   */
  @java.lang.Override
  public float getNormalizedY() {
    return normalizedY_;
  }
  /**
   * <code>float normalized_y = 6;</code>
   * @param value The normalizedY to set.
   */
  private void setNormalizedY(float value) {
    
    normalizedY_ = value;
  }
  /**
   * <code>float normalized_y = 6;</code>
   */
  private void clearNormalizedY() {

    normalizedY_ = 0F;
  }

  public static final int PRESSURE_FIELD_NUMBER = 7;
  private float pressure_;
  /**
   * <code>float pressure = 7;</code>
   * @return The pressure.
   */
  @java.lang.Override
  public float getPressure() {
    return pressure_;
  }
  /**
   * <code>float pressure = 7;</code>
   * @param value The pressure to set.
   */
  private void setPressure(float value) {
    
    pressure_ = value;
  }
  /**
   * <code>float pressure = 7;</code>
   */
  private void clearPressure() {

    pressure_ = 0F;
  }

  public static final int SCROLL_X_FIELD_NUMBER = 8;
  private float scrollX_;
  /**
   * <code>float scroll_x = 8;</code>
   * @return The scrollX.
   */
  @java.lang.Override
  public float getScrollX() {
    return scrollX_;
  }
  /**
   * <code>float scroll_x = 8;</code>
   * @param value The scrollX to set.
   */
  private void setScrollX(float value) {
    
    scrollX_ = value;
  }
  /**
   * <code>float scroll_x = 8;</code>
   */
  private void clearScrollX() {

    scrollX_ = 0F;
  }

  public static final int SCROLL_Y_FIELD_NUMBER = 9;
  private float scrollY_;
  /**
   * <code>float scroll_y = 9;</code>
   * @return The scrollY.
   */
  @java.lang.Override
  public float getScrollY() {
    return scrollY_;
  }
  /**
   * <code>float scroll_y = 9;</code>
   * @param value The scrollY to set.
   */
  private void setScrollY(float value) {
    
    scrollY_ = value;
  }
  /**
   * <code>float scroll_y = 9;</code>
   */
  private void clearScrollY() {

    scrollY_ = 0F;
  }

  public static final int BUTTONS_FIELD_NUMBER = 10;
  private int buttons_;
  /**
   * <code>uint32 buttons = 10;</code>
   * @return The buttons.
   */
  @java.lang.Override
  public int getButtons() {
    return buttons_;
  }
  /**
   * <code>uint32 buttons = 10;</code>
   * @param value The buttons to set.
   */
  private void setButtons(int value) {
    
    buttons_ = value;
  }
  /**
   * <code>uint32 buttons = 10;</code>
   */
  private void clearButtons() {

    buttons_ = 0;
  }

  public static final int ANDROID_KEYCODE_FIELD_NUMBER = 11;
  private int androidKeycode_;
  /**
   * <code>uint32 android_keycode = 11;</code>
   * @return The androidKeycode.
   */
  @java.lang.Override
  public int getAndroidKeycode() {
    return androidKeycode_;
  }
  /**
   * <code>uint32 android_keycode = 11;</code>
   * @param value The androidKeycode to set.
   */
  private void setAndroidKeycode(int value) {
    
    androidKeycode_ = value;
  }
  /**
   * <code>uint32 android_keycode = 11;</code>
   */
  private void clearAndroidKeycode() {

    androidKeycode_ = 0;
  }

  public static final int MODIFIERS_FIELD_NUMBER = 12;
  private int modifiers_;
  /**
   * <code>uint32 modifiers = 12;</code>
   * @return The modifiers.
   */
  @java.lang.Override
  public int getModifiers() {
    return modifiers_;
  }
  /**
   * <code>uint32 modifiers = 12;</code>
   * @param value The modifiers to set.
   */
  private void setModifiers(int value) {
    
    modifiers_ = value;
  }
  /**
   * <code>uint32 modifiers = 12;</code>
   */
  private void clearModifiers() {

    modifiers_ = 0;
  }

  public static final int TEXT_FIELD_NUMBER = 13;
  private java.lang.String text_;
  /**
   * <code>string text = 13;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    return text_;
  }
  /**
   * <code>string text = 13;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(text_);
  }
  /**
   * <code>string text = 13;</code>
   * @param value The text to set.
   */
  private void setText(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    text_ = value;
  }
  /**
   * <code>string text = 13;</code>
   */
  private void clearText() {

    text_ = getDefaultInstance().getText();
  }
  /**
   * <code>string text = 13;</code>
   * @param value The bytes for text to set.
   */
  private void setTextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    text_ = value.toStringUtf8();

  }

  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.InputEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.InputEvent prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.InputEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.InputEvent, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.InputEvent)
      com.xopmc.galaxybridge.protocol.v1.InputEventOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.InputEvent.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.galaxybridge.v1.InputAction action = 1;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override
    public int getActionValue() {
      return instance.getActionValue();
    }
    /**
     * <code>.galaxybridge.v1.InputAction action = 1;</code>
     * @param value The action to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setActionValue(int value) {
      copyOnWrite();
      instance.setActionValue(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.InputAction action = 1;</code>
     * @return The action.
     */
    @java.lang.Override
    public com.xopmc.galaxybridge.protocol.v1.InputAction getAction() {
      return instance.getAction();
    }
    /**
     * <code>.galaxybridge.v1.InputAction action = 1;</code>
     * @param value The enum numeric value on the wire for action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(com.xopmc.galaxybridge.protocol.v1.InputAction value) {
      copyOnWrite();
      instance.setAction(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.InputAction action = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      copyOnWrite();
      instance.clearAction();
      return this;
    }

    /**
     * <code>uint32 display_id = 2;</code>
     * @return The displayId.
     */
    @java.lang.Override
    public int getDisplayId() {
      return instance.getDisplayId();
    }
    /**
     * <code>uint32 display_id = 2;</code>
     * @param value The displayId to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayId(int value) {
      copyOnWrite();
      instance.setDisplayId(value);
      return this;
    }
    /**
     * <code>uint32 display_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayId() {
      copyOnWrite();
      instance.clearDisplayId();
      return this;
    }

    /**
     * <code>uint32 display_epoch = 3;</code>
     * @return The displayEpoch.
     */
    @java.lang.Override
    public int getDisplayEpoch() {
      return instance.getDisplayEpoch();
    }
    /**
     * <code>uint32 display_epoch = 3;</code>
     * @param value The displayEpoch to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayEpoch(int value) {
      copyOnWrite();
      instance.setDisplayEpoch(value);
      return this;
    }
    /**
     * <code>uint32 display_epoch = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayEpoch() {
      copyOnWrite();
      instance.clearDisplayEpoch();
      return this;
    }

    /**
     * <code>uint64 pointer_id = 4;</code>
     * @return The pointerId.
     */
    @java.lang.Override
    public long getPointerId() {
      return instance.getPointerId();
    }
    /**
     * <code>uint64 pointer_id = 4;</code>
     * @param value The pointerId to set.
     * @return This builder for chaining.
     */
    public Builder setPointerId(long value) {
      copyOnWrite();
      instance.setPointerId(value);
      return this;
    }
    /**
     * <code>uint64 pointer_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPointerId() {
      copyOnWrite();
      instance.clearPointerId();
      return this;
    }

    /**
     * <code>float normalized_x = 5;</code>
     * @return The normalizedX.
     */
    @java.lang.Override
    public float getNormalizedX() {
      return instance.getNormalizedX();
    }
    /**
     * <code>float normalized_x = 5;</code>
     * @param value The normalizedX to set.
     * @return This builder for chaining.
     */
    public Builder setNormalizedX(float value) {
      copyOnWrite();
      instance.setNormalizedX(value);
      return this;
    }
    /**
     * <code>float normalized_x = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNormalizedX() {
      copyOnWrite();
      instance.clearNormalizedX();
      return this;
    }

    /**
     * <code>float normalized_y = 6;</code>
     * @return The normalizedY.
     */
    @java.lang.Override
    public float getNormalizedY() {
      return instance.getNormalizedY();
    }
    /**
     * <code>float normalized_y = 6;</code>
     * @param value The normalizedY to set.
     * @return This builder for chaining.
     */
    public Builder setNormalizedY(float value) {
      copyOnWrite();
      instance.setNormalizedY(value);
      return this;
    }
    /**
     * <code>float normalized_y = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNormalizedY() {
      copyOnWrite();
      instance.clearNormalizedY();
      return this;
    }

    /**
     * <code>float pressure = 7;</code>
     * @return The pressure.
     */
    @java.lang.Override
    public float getPressure() {
      return instance.getPressure();
    }
    /**
     * <code>float pressure = 7;</code>
     * @param value The pressure to set.
     * @return This builder for chaining.
     */
    public Builder setPressure(float value) {
      copyOnWrite();
      instance.setPressure(value);
      return this;
    }
    /**
     * <code>float pressure = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPressure() {
      copyOnWrite();
      instance.clearPressure();
      return this;
    }

    /**
     * <code>float scroll_x = 8;</code>
     * @return The scrollX.
     */
    @java.lang.Override
    public float getScrollX() {
      return instance.getScrollX();
    }
    /**
     * <code>float scroll_x = 8;</code>
     * @param value The scrollX to set.
     * @return This builder for chaining.
     */
    public Builder setScrollX(float value) {
      copyOnWrite();
      instance.setScrollX(value);
      return this;
    }
    /**
     * <code>float scroll_x = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearScrollX() {
      copyOnWrite();
      instance.clearScrollX();
      return this;
    }

    /**
     * <code>float scroll_y = 9;</code>
     * @return The scrollY.
     */
    @java.lang.Override
    public float getScrollY() {
      return instance.getScrollY();
    }
    /**
     * <code>float scroll_y = 9;</code>
     * @param value The scrollY to set.
     * @return This builder for chaining.
     */
    public Builder setScrollY(float value) {
      copyOnWrite();
      instance.setScrollY(value);
      return this;
    }
    /**
     * <code>float scroll_y = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearScrollY() {
      copyOnWrite();
      instance.clearScrollY();
      return this;
    }

    /**
     * <code>uint32 buttons = 10;</code>
     * @return The buttons.
     */
    @java.lang.Override
    public int getButtons() {
      return instance.getButtons();
    }
    /**
     * <code>uint32 buttons = 10;</code>
     * @param value The buttons to set.
     * @return This builder for chaining.
     */
    public Builder setButtons(int value) {
      copyOnWrite();
      instance.setButtons(value);
      return this;
    }
    /**
     * <code>uint32 buttons = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearButtons() {
      copyOnWrite();
      instance.clearButtons();
      return this;
    }

    /**
     * <code>uint32 android_keycode = 11;</code>
     * @return The androidKeycode.
     */
    @java.lang.Override
    public int getAndroidKeycode() {
      return instance.getAndroidKeycode();
    }
    /**
     * <code>uint32 android_keycode = 11;</code>
     * @param value The androidKeycode to set.
     * @return This builder for chaining.
     */
    public Builder setAndroidKeycode(int value) {
      copyOnWrite();
      instance.setAndroidKeycode(value);
      return this;
    }
    /**
     * <code>uint32 android_keycode = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearAndroidKeycode() {
      copyOnWrite();
      instance.clearAndroidKeycode();
      return this;
    }

    /**
     * <code>uint32 modifiers = 12;</code>
     * @return The modifiers.
     */
    @java.lang.Override
    public int getModifiers() {
      return instance.getModifiers();
    }
    /**
     * <code>uint32 modifiers = 12;</code>
     * @param value The modifiers to set.
     * @return This builder for chaining.
     */
    public Builder setModifiers(int value) {
      copyOnWrite();
      instance.setModifiers(value);
      return this;
    }
    /**
     * <code>uint32 modifiers = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearModifiers() {
      copyOnWrite();
      instance.clearModifiers();
      return this;
    }

    /**
     * <code>string text = 13;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      return instance.getText();
    }
    /**
     * <code>string text = 13;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      return instance.getTextBytes();
    }
    /**
     * <code>string text = 13;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      copyOnWrite();
      instance.setText(value);
      return this;
    }
    /**
     * <code>string text = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      copyOnWrite();
      instance.clearText();
      return this;
    }
    /**
     * <code>string text = 13;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTextBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.InputEvent)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.InputEvent();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "action_",
            "displayId_",
            "displayEpoch_",
            "pointerId_",
            "normalizedX_",
            "normalizedY_",
            "pressure_",
            "scrollX_",
            "scrollY_",
            "buttons_",
            "androidKeycode_",
            "modifiers_",
            "text_",
          };
          java.lang.String info =
              "\u0000\r\u0000\u0000\u0001\r\r\u0000\u0000\u0000\u0001\f\u0002\u000b\u0003\u000b" +
              "\u0004\u0003\u0005\u0001\u0006\u0001\u0007\u0001\b\u0001\t\u0001\n\u000b\u000b\u000b" +
              "\f\u000b\r\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.InputEvent> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.InputEvent.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.InputEvent>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.InputEvent)
  private static final com.xopmc.galaxybridge.protocol.v1.InputEvent DEFAULT_INSTANCE;
  static {
    InputEvent defaultInstance = new InputEvent();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      InputEvent.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.InputEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<InputEvent> PARSER;

  public static com.google.protobuf.Parser<InputEvent> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

