// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf enum {@code galaxybridge.v1.InputAction}
 */
@com.google.protobuf.Generated
public enum InputAction
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>INPUT_ACTION_UNSPECIFIED = 0;</code>
   */
  INPUT_ACTION_UNSPECIFIED(0),
  /**
   * <code>INPUT_ACTION_DOWN = 1;</code>
   */
  INPUT_ACTION_DOWN(1),
  /**
   * <code>INPUT_ACTION_MOVE = 2;</code>
   */
  INPUT_ACTION_MOVE(2),
  /**
   * <code>INPUT_ACTION_UP = 3;</code>
   */
  INPUT_ACTION_UP(3),
  /**
   * <code>INPUT_ACTION_CANCEL = 4;</code>
   */
  INPUT_ACTION_CANCEL(4),
  /**
   * <code>INPUT_ACTION_SCROLL = 5;</code>
   */
  INPUT_ACTION_SCROLL(5),
  /**
   * <code>INPUT_ACTION_KEY = 6;</code>
   */
  INPUT_ACTION_KEY(6),
  /**
   * <code>INPUT_ACTION_TEXT = 7;</code>
   */
  INPUT_ACTION_TEXT(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>INPUT_ACTION_UNSPECIFIED = 0;</code>
   */
  public static final int INPUT_ACTION_UNSPECIFIED_VALUE = 0;
  /**
   * <code>INPUT_ACTION_DOWN = 1;</code>
   */
  public static final int INPUT_ACTION_DOWN_VALUE = 1;
  /**
   * <code>INPUT_ACTION_MOVE = 2;</code>
   */
  public static final int INPUT_ACTION_MOVE_VALUE = 2;
  /**
   * <code>INPUT_ACTION_UP = 3;</code>
   */
  public static final int INPUT_ACTION_UP_VALUE = 3;
  /**
   * <code>INPUT_ACTION_CANCEL = 4;</code>
   */
  public static final int INPUT_ACTION_CANCEL_VALUE = 4;
  /**
   * <code>INPUT_ACTION_SCROLL = 5;</code>
   */
  public static final int INPUT_ACTION_SCROLL_VALUE = 5;
  /**
   * <code>INPUT_ACTION_KEY = 6;</code>
   */
  public static final int INPUT_ACTION_KEY_VALUE = 6;
  /**
   * <code>INPUT_ACTION_TEXT = 7;</code>
   */
  public static final int INPUT_ACTION_TEXT_VALUE = 7;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static InputAction valueOf(int value) {
    return forNumber(value);
  }

  public static InputAction forNumber(int value) {
    switch (value) {
      case 0: return INPUT_ACTION_UNSPECIFIED;
      case 1: return INPUT_ACTION_DOWN;
      case 2: return INPUT_ACTION_MOVE;
      case 3: return INPUT_ACTION_UP;
      case 4: return INPUT_ACTION_CANCEL;
      case 5: return INPUT_ACTION_SCROLL;
      case 6: return INPUT_ACTION_KEY;
      case 7: return INPUT_ACTION_TEXT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<InputAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      InputAction> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<InputAction>() {
          @java.lang.Override
          public InputAction findValueByNumber(int number) {
            return InputAction.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return InputActionVerifier.INSTANCE;
  }

  private static final class InputActionVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new InputActionVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return InputAction.forNumber(number) != null;
          }
        };

  private final int value;

  private InputAction(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:galaxybridge.v1.InputAction)
}

