// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.NotificationAction}
 */
@com.google.protobuf.Generated
public  final class NotificationAction extends
    com.google.protobuf.GeneratedMessageLite<
        NotificationAction, NotificationAction.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.NotificationAction)
    NotificationActionOrBuilder {
  private NotificationAction() {
    notificationId_ = "";
    actionId_ = "";
    replyText_ = "";
  }
  public static final int NOTIFICATION_ID_FIELD_NUMBER = 1;
  private java.lang.String notificationId_;
  /**
   * <code>string notification_id = 1;</code>
   * @return The notificationId.
   */
  @java.lang.Override
  public java.lang.String getNotificationId() {
    return notificationId_;
  }
  /**
   * <code>string notification_id = 1;</code>
   * @return The bytes for notificationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNotificationIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(notificationId_);
  }
  /**
   * <code>string notification_id = 1;</code>
   * @param value The notificationId to set.
   */
  private void setNotificationId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    notificationId_ = value;
  }
  /**
   * <code>string notification_id = 1;</code>
   */
  private void clearNotificationId() {

    notificationId_ = getDefaultInstance().getNotificationId();
  }
  /**
   * <code>string notification_id = 1;</code>
   * @param value The bytes for notificationId to set.
   */
  private void setNotificationIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    notificationId_ = value.toStringUtf8();

  }

  public static final int ACTION_ID_FIELD_NUMBER = 2;
  private java.lang.String actionId_;
  /**
   * <code>string action_id = 2;</code>
   * @return The actionId.
   */
  @java.lang.Override
  public java.lang.String getActionId() {
    return actionId_;
  }
  /**
   * <code>string action_id = 2;</code>
   * @return The bytes for actionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(actionId_);
  }
  /**
   * <code>string action_id = 2;</code>
   * @param value The actionId to set.
   */
  private void setActionId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    actionId_ = value;
  }
  /**
   * <code>string action_id = 2;</code>
   */
  private void clearActionId() {

    actionId_ = getDefaultInstance().getActionId();
  }
  /**
   * <code>string action_id = 2;</code>
   * @param value The bytes for actionId to set.
   */
  private void setActionIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    actionId_ = value.toStringUtf8();

  }

  public static final int REPLY_TEXT_FIELD_NUMBER = 3;
  private java.lang.String replyText_;
  /**
   * <code>string reply_text = 3;</code>
   * @return The replyText.
   */
  @java.lang.Override
  public java.lang.String getReplyText() {
    return replyText_;
  }
  /**
   * <code>string reply_text = 3;</code>
   * @return The bytes for replyText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReplyTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(replyText_);
  }
  /**
   * <code>string reply_text = 3;</code>
   * @param value The replyText to set.
   */
  private void setReplyText(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    replyText_ = value;
  }
  /**
   * <code>string reply_text = 3;</code>
   */
  private void clearReplyText() {

    replyText_ = getDefaultInstance().getReplyText();
  }
  /**
   * <code>string reply_text = 3;</code>
   * @param value The bytes for replyText to set.
   */
  private void setReplyTextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    replyText_ = value.toStringUtf8();

  }

  public static final int DISMISS_FIELD_NUMBER = 4;
  private boolean dismiss_;
  /**
   * <code>bool dismiss = 4;</code>
   * @return The dismiss.
   */
  @java.lang.Override
  public boolean getDismiss() {
    return dismiss_;
  }
  /**
   * <code>bool dismiss = 4;</code>
   * @param value The dismiss to set.
   */
  private void setDismiss(boolean value) {
    
    dismiss_ = value;
  }
  /**
   * <code>bool dismiss = 4;</code>
   */
  private void clearDismiss() {

    dismiss_ = false;
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.NotificationAction prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.NotificationAction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.NotificationAction, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.NotificationAction)
      com.xopmc.galaxybridge.protocol.v1.NotificationActionOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.NotificationAction.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string notification_id = 1;</code>
     * @return The notificationId.
     */
    @java.lang.Override
    public java.lang.String getNotificationId() {
      return instance.getNotificationId();
    }
    /**
     * <code>string notification_id = 1;</code>
     * @return The bytes for notificationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNotificationIdBytes() {
      return instance.getNotificationIdBytes();
    }
    /**
     * <code>string notification_id = 1;</code>
     * @param value The notificationId to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationId(
        java.lang.String value) {
      copyOnWrite();
      instance.setNotificationId(value);
      return this;
    }
    /**
     * <code>string notification_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNotificationId() {
      copyOnWrite();
      instance.clearNotificationId();
      return this;
    }
    /**
     * <code>string notification_id = 1;</code>
     * @param value The bytes for notificationId to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNotificationIdBytes(value);
      return this;
    }

    /**
     * <code>string action_id = 2;</code>
     * @return The actionId.
     */
    @java.lang.Override
    public java.lang.String getActionId() {
      return instance.getActionId();
    }
    /**
     * <code>string action_id = 2;</code>
     * @return The bytes for actionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionIdBytes() {
      return instance.getActionIdBytes();
    }
    /**
     * <code>string action_id = 2;</code>
     * @param value The actionId to set.
     * @return This builder for chaining.
     */
    public Builder setActionId(
        java.lang.String value) {
      copyOnWrite();
      instance.setActionId(value);
      return this;
    }
    /**
     * <code>string action_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearActionId() {
      copyOnWrite();
      instance.clearActionId();
      return this;
    }
    /**
     * <code>string action_id = 2;</code>
     * @param value The bytes for actionId to set.
     * @return This builder for chaining.
     */
    public Builder setActionIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setActionIdBytes(value);
      return this;
    }

    /**
     * <code>string reply_text = 3;</code>
     * @return The replyText.
     */
    @java.lang.Override
    public java.lang.String getReplyText() {
      return instance.getReplyText();
    }
    /**
     * <code>string reply_text = 3;</code>
     * @return The bytes for replyText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReplyTextBytes() {
      return instance.getReplyTextBytes();
    }
    /**
     * <code>string reply_text = 3;</code>
     * @param value The replyText to set.
     * @return This builder for chaining.
     */
    public Builder setReplyText(
        java.lang.String value) {
      copyOnWrite();
      instance.setReplyText(value);
      return this;
    }
    /**
     * <code>string reply_text = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplyText() {
      copyOnWrite();
      instance.clearReplyText();
      return this;
    }
    /**
     * <code>string reply_text = 3;</code>
     * @param value The bytes for replyText to set.
     * @return This builder for chaining.
     */
    public Builder setReplyTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReplyTextBytes(value);
      return this;
    }

    /**
     * <code>bool dismiss = 4;</code>
     * @return The dismiss.
     */
    @java.lang.Override
    public boolean getDismiss() {
      return instance.getDismiss();
    }
    /**
     * <code>bool dismiss = 4;</code>
     * @param value The dismiss to set.
     * @return This builder for chaining.
     */
    public Builder setDismiss(boolean value) {
      copyOnWrite();
      instance.setDismiss(value);
      return this;
    }
    /**
     * <code>bool dismiss = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDismiss() {
      copyOnWrite();
      instance.clearDismiss();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.NotificationAction)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.NotificationAction();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "notificationId_",
            "actionId_",
            "replyText_",
            "dismiss_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.NotificationAction> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.NotificationAction.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.NotificationAction>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.NotificationAction)
  private static final com.xopmc.galaxybridge.protocol.v1.NotificationAction DEFAULT_INSTANCE;
  static {
    NotificationAction defaultInstance = new NotificationAction();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      NotificationAction.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationAction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NotificationAction> PARSER;

  public static com.google.protobuf.Parser<NotificationAction> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

