// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface NotificationActionDescriptorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.NotificationActionDescriptor)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string action_id = 1;</code>
   * @return The actionId.
   */
  java.lang.String getActionId();
  /**
   * <code>string action_id = 1;</code>
   * @return The bytes for actionId.
   */
  com.google.protobuf.ByteString
      getActionIdBytes();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>bool accepts_text = 3;</code>
   * @return The acceptsText.
   */
  boolean getAcceptsText();
}
