// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.NotificationEvent}
 */
@com.google.protobuf.Generated
public  final class NotificationEvent extends
    com.google.protobuf.GeneratedMessageLite<
        NotificationEvent, NotificationEvent.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.NotificationEvent)
    NotificationEventOrBuilder {
  private NotificationEvent() {
    notificationId_ = "";
    packageName_ = "";
    appLabel_ = "";
    title_ = "";
    body_ = "";
    actions_ = emptyProtobufList();
    appIconPng_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int NOTIFICATION_ID_FIELD_NUMBER = 1;
  private java.lang.String notificationId_;
  /**
   * <code>string notification_id = 1;</code>
   * @return The notificationId.
   */
  @java.lang.Override
  public java.lang.String getNotificationId() {
    return notificationId_;
  }
  /**
   * <code>string notification_id = 1;</code>
   * @return The bytes for notificationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNotificationIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(notificationId_);
  }
  /**
   * <code>string notification_id = 1;</code>
   * @param value The notificationId to set.
   */
  private void setNotificationId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    notificationId_ = value;
  }
  /**
   * <code>string notification_id = 1;</code>
   */
  private void clearNotificationId() {

    notificationId_ = getDefaultInstance().getNotificationId();
  }
  /**
   * <code>string notification_id = 1;</code>
   * @param value The bytes for notificationId to set.
   */
  private void setNotificationIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    notificationId_ = value.toStringUtf8();

  }

  public static final int PACKAGE_NAME_FIELD_NUMBER = 2;
  private java.lang.String packageName_;
  /**
   * <code>string package_name = 2;</code>
   * @return The packageName.
   */
  @java.lang.Override
  public java.lang.String getPackageName() {
    return packageName_;
  }
  /**
   * <code>string package_name = 2;</code>
   * @return The bytes for packageName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(packageName_);
  }
  /**
   * <code>string package_name = 2;</code>
   * @param value The packageName to set.
   */
  private void setPackageName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    packageName_ = value;
  }
  /**
   * <code>string package_name = 2;</code>
   */
  private void clearPackageName() {

    packageName_ = getDefaultInstance().getPackageName();
  }
  /**
   * <code>string package_name = 2;</code>
   * @param value The bytes for packageName to set.
   */
  private void setPackageNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    packageName_ = value.toStringUtf8();

  }

  public static final int APP_LABEL_FIELD_NUMBER = 3;
  private java.lang.String appLabel_;
  /**
   * <code>string app_label = 3;</code>
   * @return The appLabel.
   */
  @java.lang.Override
  public java.lang.String getAppLabel() {
    return appLabel_;
  }
  /**
   * <code>string app_label = 3;</code>
   * @return The bytes for appLabel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(appLabel_);
  }
  /**
   * <code>string app_label = 3;</code>
   * @param value The appLabel to set.
   */
  private void setAppLabel(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    appLabel_ = value;
  }
  /**
   * <code>string app_label = 3;</code>
   */
  private void clearAppLabel() {

    appLabel_ = getDefaultInstance().getAppLabel();
  }
  /**
   * <code>string app_label = 3;</code>
   * @param value The bytes for appLabel to set.
   */
  private void setAppLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    appLabel_ = value.toStringUtf8();

  }

  public static final int TITLE_FIELD_NUMBER = 4;
  private java.lang.String title_;
  /**
   * <code>string title = 4;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <code>string title = 4;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <code>string title = 4;</code>
   * @param value The title to set.
   */
  private void setTitle(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    title_ = value;
  }
  /**
   * <code>string title = 4;</code>
   */
  private void clearTitle() {

    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <code>string title = 4;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();

  }

  public static final int BODY_FIELD_NUMBER = 5;
  private java.lang.String body_;
  /**
   * <code>string body = 5;</code>
   * @return The body.
   */
  @java.lang.Override
  public java.lang.String getBody() {
    return body_;
  }
  /**
   * <code>string body = 5;</code>
   * @return The bytes for body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBodyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(body_);
  }
  /**
   * <code>string body = 5;</code>
   * @param value The body to set.
   */
  private void setBody(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    body_ = value;
  }
  /**
   * <code>string body = 5;</code>
   */
  private void clearBody() {

    body_ = getDefaultInstance().getBody();
  }
  /**
   * <code>string body = 5;</code>
   * @param value The bytes for body to set.
   */
  private void setBodyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    body_ = value.toStringUtf8();

  }

  public static final int POSTED_AT_UNIX_MS_FIELD_NUMBER = 6;
  private long postedAtUnixMs_;
  /**
   * <code>int64 posted_at_unix_ms = 6;</code>
   * @return The postedAtUnixMs.
   */
  @java.lang.Override
  public long getPostedAtUnixMs() {
    return postedAtUnixMs_;
  }
  /**
   * <code>int64 posted_at_unix_ms = 6;</code>
   * @param value The postedAtUnixMs to set.
   */
  private void setPostedAtUnixMs(long value) {
    
    postedAtUnixMs_ = value;
  }
  /**
   * <code>int64 posted_at_unix_ms = 6;</code>
   */
  private void clearPostedAtUnixMs() {

    postedAtUnixMs_ = 0L;
  }

  public static final int ACTIONS_FIELD_NUMBER = 7;
  private com.google.protobuf.Internal.ProtobufList<com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor> actions_;
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor> getActionsList() {
    return actions_;
  }
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  public java.util.List<? extends com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptorOrBuilder> 
      getActionsOrBuilderList() {
    return actions_;
  }
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  @java.lang.Override
  public int getActionsCount() {
    return actions_.size();
  }
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  @java.lang.Override
  public com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor getActions(int index) {
    return actions_.get(index);
  }
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  public com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptorOrBuilder getActionsOrBuilder(
      int index) {
    return actions_.get(index);
  }
  private void ensureActionsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor> tmp = actions_;
    if (!tmp.isModifiable()) {
      actions_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  private void setActions(
      int index, com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor value) {
    java.util.Objects.requireNonNull(value);
    ensureActionsIsMutable();
    actions_.set(index, value);
  }
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  private void addActions(com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor value) {
    java.util.Objects.requireNonNull(value);
    ensureActionsIsMutable();
    actions_.add(value);
  }
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  private void addActions(
      int index, com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor value) {
    java.util.Objects.requireNonNull(value);
    ensureActionsIsMutable();
    actions_.add(index, value);
  }
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  private void addAllActions(
      java.lang.Iterable<? extends com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor> values) {
    ensureActionsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, actions_);
  }
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  private void clearActions() {
    actions_ = emptyProtobufList();
  }
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  private void removeActions(int index) {
    ensureActionsIsMutable();
    actions_.remove(index);
  }

  public static final int REMOVED_FIELD_NUMBER = 8;
  private boolean removed_;
  /**
   * <code>bool removed = 8;</code>
   * @return The removed.
   */
  @java.lang.Override
  public boolean getRemoved() {
    return removed_;
  }
  /**
   * <code>bool removed = 8;</code>
   * @param value The removed to set.
   */
  private void setRemoved(boolean value) {
    
    removed_ = value;
  }
  /**
   * <code>bool removed = 8;</code>
   */
  private void clearRemoved() {

    removed_ = false;
  }

  public static final int APP_ICON_PNG_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString appIconPng_;
  /**
   * <code>bytes app_icon_png = 9;</code>
   * @return The appIconPng.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAppIconPng() {
    return appIconPng_;
  }
  /**
   * <code>bytes app_icon_png = 9;</code>
   * @param value The appIconPng to set.
   */
  private void setAppIconPng(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    appIconPng_ = value;
  }
  /**
   * <code>bytes app_icon_png = 9;</code>
   */
  private void clearAppIconPng() {

    appIconPng_ = getDefaultInstance().getAppIconPng();
  }

  public static final int INITIAL_SNAPSHOT_FIELD_NUMBER = 10;
  private boolean initialSnapshot_;
  /**
   * <pre>
   * True only when a newly opened events channel is replaying notifications
   * that were already active on the phone. They restore the Mac in-app list
   * but must not generate a fresh native macOS banner.
   * </pre>
   *
   * <code>bool initial_snapshot = 10;</code>
   * @return The initialSnapshot.
   */
  @java.lang.Override
  public boolean getInitialSnapshot() {
    return initialSnapshot_;
  }
  /**
   * <pre>
   * True only when a newly opened events channel is replaying notifications
   * that were already active on the phone. They restore the Mac in-app list
   * but must not generate a fresh native macOS banner.
   * </pre>
   *
   * <code>bool initial_snapshot = 10;</code>
   * @param value The initialSnapshot to set.
   */
  private void setInitialSnapshot(boolean value) {
    
    initialSnapshot_ = value;
  }
  /**
   * <pre>
   * True only when a newly opened events channel is replaying notifications
   * that were already active on the phone. They restore the Mac in-app list
   * but must not generate a fresh native macOS banner.
   * </pre>
   *
   * <code>bool initial_snapshot = 10;</code>
   */
  private void clearInitialSnapshot() {

    initialSnapshot_ = false;
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.NotificationEvent prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.NotificationEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.NotificationEvent, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.NotificationEvent)
      com.xopmc.galaxybridge.protocol.v1.NotificationEventOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.NotificationEvent.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string notification_id = 1;</code>
     * @return The notificationId.
     */
    @java.lang.Override
    public java.lang.String getNotificationId() {
      return instance.getNotificationId();
    }
    /**
     * <code>string notification_id = 1;</code>
     * @return The bytes for notificationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNotificationIdBytes() {
      return instance.getNotificationIdBytes();
    }
    /**
     * <code>string notification_id = 1;</code>
     * @param value The notificationId to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationId(
        java.lang.String value) {
      copyOnWrite();
      instance.setNotificationId(value);
      return this;
    }
    /**
     * <code>string notification_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNotificationId() {
      copyOnWrite();
      instance.clearNotificationId();
      return this;
    }
    /**
     * <code>string notification_id = 1;</code>
     * @param value The bytes for notificationId to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNotificationIdBytes(value);
      return this;
    }

    /**
     * <code>string package_name = 2;</code>
     * @return The packageName.
     */
    @java.lang.Override
    public java.lang.String getPackageName() {
      return instance.getPackageName();
    }
    /**
     * <code>string package_name = 2;</code>
     * @return The bytes for packageName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      return instance.getPackageNameBytes();
    }
    /**
     * <code>string package_name = 2;</code>
     * @param value The packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageName(
        java.lang.String value) {
      copyOnWrite();
      instance.setPackageName(value);
      return this;
    }
    /**
     * <code>string package_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageName() {
      copyOnWrite();
      instance.clearPackageName();
      return this;
    }
    /**
     * <code>string package_name = 2;</code>
     * @param value The bytes for packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPackageNameBytes(value);
      return this;
    }

    /**
     * <code>string app_label = 3;</code>
     * @return The appLabel.
     */
    @java.lang.Override
    public java.lang.String getAppLabel() {
      return instance.getAppLabel();
    }
    /**
     * <code>string app_label = 3;</code>
     * @return The bytes for appLabel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppLabelBytes() {
      return instance.getAppLabelBytes();
    }
    /**
     * <code>string app_label = 3;</code>
     * @param value The appLabel to set.
     * @return This builder for chaining.
     */
    public Builder setAppLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setAppLabel(value);
      return this;
    }
    /**
     * <code>string app_label = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppLabel() {
      copyOnWrite();
      instance.clearAppLabel();
      return this;
    }
    /**
     * <code>string app_label = 3;</code>
     * @param value The bytes for appLabel to set.
     * @return This builder for chaining.
     */
    public Builder setAppLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAppLabelBytes(value);
      return this;
    }

    /**
     * <code>string title = 4;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <code>string title = 4;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <code>string title = 4;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <code>string title = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <code>string title = 4;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>string body = 5;</code>
     * @return The body.
     */
    @java.lang.Override
    public java.lang.String getBody() {
      return instance.getBody();
    }
    /**
     * <code>string body = 5;</code>
     * @return The bytes for body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBodyBytes() {
      return instance.getBodyBytes();
    }
    /**
     * <code>string body = 5;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(
        java.lang.String value) {
      copyOnWrite();
      instance.setBody(value);
      return this;
    }
    /**
     * <code>string body = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      copyOnWrite();
      instance.clearBody();
      return this;
    }
    /**
     * <code>string body = 5;</code>
     * @param value The bytes for body to set.
     * @return This builder for chaining.
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBodyBytes(value);
      return this;
    }

    /**
     * <code>int64 posted_at_unix_ms = 6;</code>
     * @return The postedAtUnixMs.
     */
    @java.lang.Override
    public long getPostedAtUnixMs() {
      return instance.getPostedAtUnixMs();
    }
    /**
     * <code>int64 posted_at_unix_ms = 6;</code>
     * @param value The postedAtUnixMs to set.
     * @return This builder for chaining.
     */
    public Builder setPostedAtUnixMs(long value) {
      copyOnWrite();
      instance.setPostedAtUnixMs(value);
      return this;
    }
    /**
     * <code>int64 posted_at_unix_ms = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPostedAtUnixMs() {
      copyOnWrite();
      instance.clearPostedAtUnixMs();
      return this;
    }

    /**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    @java.lang.Override
    public java.util.List<com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor> getActionsList() {
      return java.util.Collections.unmodifiableList(
          instance.getActionsList());
    }
    /**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    @java.lang.Override
    public int getActionsCount() {
      return instance.getActionsCount();
    }/**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    @java.lang.Override
    public com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor getActions(int index) {
      return instance.getActions(index);
    }
    /**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    public Builder setActions(
        int index, com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor value) {
      copyOnWrite();
      instance.setActions(index, value);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    public Builder setActions(
        int index, com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor.Builder builderForValue) {
      copyOnWrite();
      instance.setActions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    public Builder addActions(com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor value) {
      copyOnWrite();
      instance.addActions(value);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    public Builder addActions(
        int index, com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor value) {
      copyOnWrite();
      instance.addActions(index, value);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    public Builder addActions(
        com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor.Builder builderForValue) {
      copyOnWrite();
      instance.addActions(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    public Builder addActions(
        int index, com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor.Builder builderForValue) {
      copyOnWrite();
      instance.addActions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    public Builder addAllActions(
        java.lang.Iterable<? extends com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor> values) {
      copyOnWrite();
      instance.addAllActions(values);
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    public Builder clearActions() {
      copyOnWrite();
      instance.clearActions();
      return this;
    }
    /**
     * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
     */
    public Builder removeActions(int index) {
      copyOnWrite();
      instance.removeActions(index);
      return this;
    }

    /**
     * <code>bool removed = 8;</code>
     * @return The removed.
     */
    @java.lang.Override
    public boolean getRemoved() {
      return instance.getRemoved();
    }
    /**
     * <code>bool removed = 8;</code>
     * @param value The removed to set.
     * @return This builder for chaining.
     */
    public Builder setRemoved(boolean value) {
      copyOnWrite();
      instance.setRemoved(value);
      return this;
    }
    /**
     * <code>bool removed = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemoved() {
      copyOnWrite();
      instance.clearRemoved();
      return this;
    }

    /**
     * <code>bytes app_icon_png = 9;</code>
     * @return The appIconPng.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAppIconPng() {
      return instance.getAppIconPng();
    }
    /**
     * <code>bytes app_icon_png = 9;</code>
     * @param value The appIconPng to set.
     * @return This builder for chaining.
     */
    public Builder setAppIconPng(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAppIconPng(value);
      return this;
    }
    /**
     * <code>bytes app_icon_png = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppIconPng() {
      copyOnWrite();
      instance.clearAppIconPng();
      return this;
    }

    /**
     * <pre>
     * True only when a newly opened events channel is replaying notifications
     * that were already active on the phone. They restore the Mac in-app list
     * but must not generate a fresh native macOS banner.
     * </pre>
     *
     * <code>bool initial_snapshot = 10;</code>
     * @return The initialSnapshot.
     */
    @java.lang.Override
    public boolean getInitialSnapshot() {
      return instance.getInitialSnapshot();
    }
    /**
     * <pre>
     * True only when a newly opened events channel is replaying notifications
     * that were already active on the phone. They restore the Mac in-app list
     * but must not generate a fresh native macOS banner.
     * </pre>
     *
     * <code>bool initial_snapshot = 10;</code>
     * @param value The initialSnapshot to set.
     * @return This builder for chaining.
     */
    public Builder setInitialSnapshot(boolean value) {
      copyOnWrite();
      instance.setInitialSnapshot(value);
      return this;
    }
    /**
     * <pre>
     * True only when a newly opened events channel is replaying notifications
     * that were already active on the phone. They restore the Mac in-app list
     * but must not generate a fresh native macOS banner.
     * </pre>
     *
     * <code>bool initial_snapshot = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitialSnapshot() {
      copyOnWrite();
      instance.clearInitialSnapshot();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.NotificationEvent)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.NotificationEvent();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "notificationId_",
            "packageName_",
            "appLabel_",
            "title_",
            "body_",
            "postedAtUnixMs_",
            "actions_",
            com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor.class,
            "removed_",
            "appIconPng_",
            "initialSnapshot_",
          };
          java.lang.String info =
              "\u0000\n\u0000\u0000\u0001\n\n\u0000\u0001\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\u0208\u0005\u0208\u0006\u0002\u0007\u001b\b\u0007\t\n\n\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.NotificationEvent> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.NotificationEvent.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.NotificationEvent>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.NotificationEvent)
  private static final com.xopmc.galaxybridge.protocol.v1.NotificationEvent DEFAULT_INSTANCE;
  static {
    NotificationEvent defaultInstance = new NotificationEvent();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      NotificationEvent.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NotificationEvent> PARSER;

  public static com.google.protobuf.Parser<NotificationEvent> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

