// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.NotificationActionDescriptor}
 */
@com.google.protobuf.Generated
public  final class NotificationActionDescriptor extends
    com.google.protobuf.GeneratedMessageLite<
        NotificationActionDescriptor, NotificationActionDescriptor.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.NotificationActionDescriptor)
    NotificationActionDescriptorOrBuilder {
  private NotificationActionDescriptor() {
    actionId_ = "";
    title_ = "";
  }
  public static final int ACTION_ID_FIELD_NUMBER = 1;
  private java.lang.String actionId_;
  /**
   * <code>string action_id = 1;</code>
   * @return The actionId.
   */
  @java.lang.Override
  public java.lang.String getActionId() {
    return actionId_;
  }
  /**
   * <code>string action_id = 1;</code>
   * @return The bytes for actionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(actionId_);
  }
  /**
   * <code>string action_id = 1;</code>
   * @param value The actionId to set.
   */
  private void setActionId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    actionId_ = value;
  }
  /**
   * <code>string action_id = 1;</code>
   */
  private void clearActionId() {

    actionId_ = getDefaultInstance().getActionId();
  }
  /**
   * <code>string action_id = 1;</code>
   * @param value The bytes for actionId to set.
   */
  private void setActionIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    actionId_ = value.toStringUtf8();

  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private java.lang.String title_;
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <code>string title = 2;</code>
   * @param value The title to set.
   */
  private void setTitle(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    title_ = value;
  }
  /**
   * <code>string title = 2;</code>
   */
  private void clearTitle() {

    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <code>string title = 2;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();

  }

  public static final int ACCEPTS_TEXT_FIELD_NUMBER = 3;
  private boolean acceptsText_;
  /**
   * <code>bool accepts_text = 3;</code>
   * @return The acceptsText.
   */
  @java.lang.Override
  public boolean getAcceptsText() {
    return acceptsText_;
  }
  /**
   * <code>bool accepts_text = 3;</code>
   * @param value The acceptsText to set.
   */
  private void setAcceptsText(boolean value) {
    
    acceptsText_ = value;
  }
  /**
   * <code>bool accepts_text = 3;</code>
   */
  private void clearAcceptsText() {

    acceptsText_ = false;
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.NotificationActionDescriptor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.NotificationActionDescriptor)
      com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptorOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string action_id = 1;</code>
     * @return The actionId.
     */
    @java.lang.Override
    public java.lang.String getActionId() {
      return instance.getActionId();
    }
    /**
     * <code>string action_id = 1;</code>
     * @return The bytes for actionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionIdBytes() {
      return instance.getActionIdBytes();
    }
    /**
     * <code>string action_id = 1;</code>
     * @param value The actionId to set.
     * @return This builder for chaining.
     */
    public Builder setActionId(
        java.lang.String value) {
      copyOnWrite();
      instance.setActionId(value);
      return this;
    }
    /**
     * <code>string action_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearActionId() {
      copyOnWrite();
      instance.clearActionId();
      return this;
    }
    /**
     * <code>string action_id = 1;</code>
     * @param value The bytes for actionId to set.
     * @return This builder for chaining.
     */
    public Builder setActionIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setActionIdBytes(value);
      return this;
    }

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>bool accepts_text = 3;</code>
     * @return The acceptsText.
     */
    @java.lang.Override
    public boolean getAcceptsText() {
      return instance.getAcceptsText();
    }
    /**
     * <code>bool accepts_text = 3;</code>
     * @param value The acceptsText to set.
     * @return This builder for chaining.
     */
    public Builder setAcceptsText(boolean value) {
      copyOnWrite();
      instance.setAcceptsText(value);
      return this;
    }
    /**
     * <code>bool accepts_text = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAcceptsText() {
      copyOnWrite();
      instance.clearAcceptsText();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.NotificationActionDescriptor)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "actionId_",
            "title_",
            "acceptsText_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.NotificationActionDescriptor)
  private static final com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor DEFAULT_INSTANCE;
  static {
    NotificationActionDescriptor defaultInstance = new NotificationActionDescriptor();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      NotificationActionDescriptor.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NotificationActionDescriptor> PARSER;

  public static com.google.protobuf.Parser<NotificationActionDescriptor> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

