// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface NotificationActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.NotificationAction)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string notification_id = 1;</code>
   * @return The notificationId.
   */
  java.lang.String getNotificationId();
  /**
   * <code>string notification_id = 1;</code>
   * @return The bytes for notificationId.
   */
  com.google.protobuf.ByteString
      getNotificationIdBytes();

  /**
   * <code>string action_id = 2;</code>
   * @return The actionId.
   */
  java.lang.String getActionId();
  /**
   * <code>string action_id = 2;</code>
   * @return The bytes for actionId.
   */
  com.google.protobuf.ByteString
      getActionIdBytes();

  /**
   * <code>string reply_text = 3;</code>
   * @return The replyText.
   */
  java.lang.String getReplyText();
  /**
   * <code>string reply_text = 3;</code>
   * @return The bytes for replyText.
   */
  com.google.protobuf.ByteString
      getReplyTextBytes();

  /**
   * <code>bool dismiss = 4;</code>
   * @return The dismiss.
   */
  boolean getDismiss();
}
