// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface NotificationEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.NotificationEvent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string notification_id = 1;</code>
   * @return The notificationId.
   */
  java.lang.String getNotificationId();
  /**
   * <code>string notification_id = 1;</code>
   * @return The bytes for notificationId.
   */
  com.google.protobuf.ByteString
      getNotificationIdBytes();

  /**
   * <code>string package_name = 2;</code>
   * @return The packageName.
   */
  java.lang.String getPackageName();
  /**
   * <code>string package_name = 2;</code>
   * @return The bytes for packageName.
   */
  com.google.protobuf.ByteString
      getPackageNameBytes();

  /**
   * <code>string app_label = 3;</code>
   * @return The appLabel.
   */
  java.lang.String getAppLabel();
  /**
   * <code>string app_label = 3;</code>
   * @return The bytes for appLabel.
   */
  com.google.protobuf.ByteString
      getAppLabelBytes();

  /**
   * <code>string title = 4;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 4;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string body = 5;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 5;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>int64 posted_at_unix_ms = 6;</code>
   * @return The postedAtUnixMs.
   */
  long getPostedAtUnixMs();

  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  java.util.List<com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor> 
      getActionsList();
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  com.xopmc.galaxybridge.protocol.v1.NotificationActionDescriptor getActions(int index);
  /**
   * <code>repeated .galaxybridge.v1.NotificationActionDescriptor actions = 7;</code>
   */
  int getActionsCount();

  /**
   * <code>bool removed = 8;</code>
   * @return The removed.
   */
  boolean getRemoved();

  /**
   * <code>bytes app_icon_png = 9;</code>
   * @return The appIconPng.
   */
  com.google.protobuf.ByteString getAppIconPng();

  /**
   * <pre>
   * True only when a newly opened events channel is replaying notifications
   * that were already active on the phone. They restore the Mac in-app list
   * but must not generate a fresh native macOS banner.
   * </pre>
   *
   * <code>bool initial_snapshot = 10;</code>
   * @return The initialSnapshot.
   */
  boolean getInitialSnapshot();
}
