// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.OpenChannel}
 */
@com.google.protobuf.Generated
public  final class OpenChannel extends
    com.google.protobuf.GeneratedMessageLite<
        OpenChannel, OpenChannel.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.OpenChannel)
    OpenChannelOrBuilder {
  private OpenChannel() {
    streamId_ = "";
    codec_ = "";
  }
  public static final int KIND_FIELD_NUMBER = 1;
  private int kind_;
  /**
   * <code>.galaxybridge.v1.ChannelKind kind = 1;</code>
   * @return The enum numeric value on the wire for kind.
   */
  @java.lang.Override
  public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.galaxybridge.v1.ChannelKind kind = 1;</code>
   * @return The kind.
   */
  @java.lang.Override
  public com.xopmc.galaxybridge.protocol.v1.ChannelKind getKind() {
    com.xopmc.galaxybridge.protocol.v1.ChannelKind result = com.xopmc.galaxybridge.protocol.v1.ChannelKind.forNumber(kind_);
    return result == null ? com.xopmc.galaxybridge.protocol.v1.ChannelKind.UNRECOGNIZED : result;
  }
  /**
   * <code>.galaxybridge.v1.ChannelKind kind = 1;</code>
   * @param value The enum numeric value on the wire for kind to set.
   */
  private void setKindValue(int value) {
      kind_ = value;
  }
  /**
   * <code>.galaxybridge.v1.ChannelKind kind = 1;</code>
   * @param value The kind to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setKind(com.xopmc.galaxybridge.protocol.v1.ChannelKind value) {
    kind_ = value.getNumber();

  }
  /**
   * <code>.galaxybridge.v1.ChannelKind kind = 1;</code>
   */
  private void clearKind() {

    kind_ = 0;
  }

  public static final int STREAM_ID_FIELD_NUMBER = 2;
  private java.lang.String streamId_;
  /**
   * <code>string stream_id = 2;</code>
   * @return The streamId.
   */
  @java.lang.Override
  public java.lang.String getStreamId() {
    return streamId_;
  }
  /**
   * <code>string stream_id = 2;</code>
   * @return The bytes for streamId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStreamIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(streamId_);
  }
  /**
   * <code>string stream_id = 2;</code>
   * @param value The streamId to set.
   */
  private void setStreamId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    streamId_ = value;
  }
  /**
   * <code>string stream_id = 2;</code>
   */
  private void clearStreamId() {

    streamId_ = getDefaultInstance().getStreamId();
  }
  /**
   * <code>string stream_id = 2;</code>
   * @param value The bytes for streamId to set.
   */
  private void setStreamIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    streamId_ = value.toStringUtf8();

  }

  public static final int CODEC_FIELD_NUMBER = 3;
  private java.lang.String codec_;
  /**
   * <code>string codec = 3;</code>
   * @return The codec.
   */
  @java.lang.Override
  public java.lang.String getCodec() {
    return codec_;
  }
  /**
   * <code>string codec = 3;</code>
   * @return The bytes for codec.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodecBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(codec_);
  }
  /**
   * <code>string codec = 3;</code>
   * @param value The codec to set.
   */
  private void setCodec(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    codec_ = value;
  }
  /**
   * <code>string codec = 3;</code>
   */
  private void clearCodec() {

    codec_ = getDefaultInstance().getCodec();
  }
  /**
   * <code>string codec = 3;</code>
   * @param value The bytes for codec to set.
   */
  private void setCodecBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    codec_ = value.toStringUtf8();

  }

  public static final int DISPLAY_ID_FIELD_NUMBER = 4;
  private int displayId_;
  /**
   * <code>uint32 display_id = 4;</code>
   * @return The displayId.
   */
  @java.lang.Override
  public int getDisplayId() {
    return displayId_;
  }
  /**
   * <code>uint32 display_id = 4;</code>
   * @param value The displayId to set.
   */
  private void setDisplayId(int value) {
    
    displayId_ = value;
  }
  /**
   * <code>uint32 display_id = 4;</code>
   */
  private void clearDisplayId() {

    displayId_ = 0;
  }

  public static final int EPOCH_FIELD_NUMBER = 5;
  private int epoch_;
  /**
   * <code>uint32 epoch = 5;</code>
   * @return The epoch.
   */
  @java.lang.Override
  public int getEpoch() {
    return epoch_;
  }
  /**
   * <code>uint32 epoch = 5;</code>
   * @param value The epoch to set.
   */
  private void setEpoch(int value) {
    
    epoch_ = value;
  }
  /**
   * <code>uint32 epoch = 5;</code>
   */
  private void clearEpoch() {

    epoch_ = 0;
  }

  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.OpenChannel prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.OpenChannel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.OpenChannel, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.OpenChannel)
      com.xopmc.galaxybridge.protocol.v1.OpenChannelOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.OpenChannel.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.galaxybridge.v1.ChannelKind kind = 1;</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override
    public int getKindValue() {
      return instance.getKindValue();
    }
    /**
     * <code>.galaxybridge.v1.ChannelKind kind = 1;</code>
     * @param value The kind to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setKindValue(int value) {
      copyOnWrite();
      instance.setKindValue(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.ChannelKind kind = 1;</code>
     * @return The kind.
     */
    @java.lang.Override
    public com.xopmc.galaxybridge.protocol.v1.ChannelKind getKind() {
      return instance.getKind();
    }
    /**
     * <code>.galaxybridge.v1.ChannelKind kind = 1;</code>
     * @param value The enum numeric value on the wire for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(com.xopmc.galaxybridge.protocol.v1.ChannelKind value) {
      copyOnWrite();
      instance.setKind(value);
      return this;
    }
    /**
     * <code>.galaxybridge.v1.ChannelKind kind = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      copyOnWrite();
      instance.clearKind();
      return this;
    }

    /**
     * <code>string stream_id = 2;</code>
     * @return The streamId.
     */
    @java.lang.Override
    public java.lang.String getStreamId() {
      return instance.getStreamId();
    }
    /**
     * <code>string stream_id = 2;</code>
     * @return The bytes for streamId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreamIdBytes() {
      return instance.getStreamIdBytes();
    }
    /**
     * <code>string stream_id = 2;</code>
     * @param value The streamId to set.
     * @return This builder for chaining.
     */
    public Builder setStreamId(
        java.lang.String value) {
      copyOnWrite();
      instance.setStreamId(value);
      return this;
    }
    /**
     * <code>string stream_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreamId() {
      copyOnWrite();
      instance.clearStreamId();
      return this;
    }
    /**
     * <code>string stream_id = 2;</code>
     * @param value The bytes for streamId to set.
     * @return This builder for chaining.
     */
    public Builder setStreamIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStreamIdBytes(value);
      return this;
    }

    /**
     * <code>string codec = 3;</code>
     * @return The codec.
     */
    @java.lang.Override
    public java.lang.String getCodec() {
      return instance.getCodec();
    }
    /**
     * <code>string codec = 3;</code>
     * @return The bytes for codec.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodecBytes() {
      return instance.getCodecBytes();
    }
    /**
     * <code>string codec = 3;</code>
     * @param value The codec to set.
     * @return This builder for chaining.
     */
    public Builder setCodec(
        java.lang.String value) {
      copyOnWrite();
      instance.setCodec(value);
      return this;
    }
    /**
     * <code>string codec = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodec() {
      copyOnWrite();
      instance.clearCodec();
      return this;
    }
    /**
     * <code>string codec = 3;</code>
     * @param value The bytes for codec to set.
     * @return This builder for chaining.
     */
    public Builder setCodecBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCodecBytes(value);
      return this;
    }

    /**
     * <code>uint32 display_id = 4;</code>
     * @return The displayId.
     */
    @java.lang.Override
    public int getDisplayId() {
      return instance.getDisplayId();
    }
    /**
     * <code>uint32 display_id = 4;</code>
     * @param value The displayId to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayId(int value) {
      copyOnWrite();
      instance.setDisplayId(value);
      return this;
    }
    /**
     * <code>uint32 display_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayId() {
      copyOnWrite();
      instance.clearDisplayId();
      return this;
    }

    /**
     * <code>uint32 epoch = 5;</code>
     * @return The epoch.
     */
    @java.lang.Override
    public int getEpoch() {
      return instance.getEpoch();
    }
    /**
     * <code>uint32 epoch = 5;</code>
     * @param value The epoch to set.
     * @return This builder for chaining.
     */
    public Builder setEpoch(int value) {
      copyOnWrite();
      instance.setEpoch(value);
      return this;
    }
    /**
     * <code>uint32 epoch = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpoch() {
      copyOnWrite();
      instance.clearEpoch();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.OpenChannel)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.OpenChannel();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "kind_",
            "streamId_",
            "codec_",
            "displayId_",
            "epoch_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\f\u0002\u0208" +
              "\u0003\u0208\u0004\u000b\u0005\u000b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.OpenChannel> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.OpenChannel.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.OpenChannel>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.OpenChannel)
  private static final com.xopmc.galaxybridge.protocol.v1.OpenChannel DEFAULT_INSTANCE;
  static {
    OpenChannel defaultInstance = new OpenChannel();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      OpenChannel.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.OpenChannel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<OpenChannel> PARSER;

  public static com.google.protobuf.Parser<OpenChannel> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

