// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.PairingCommit}
 */
@com.google.protobuf.Generated
public  final class PairingCommit extends
    com.google.protobuf.GeneratedMessageLite<
        PairingCommit, PairingCommit.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.PairingCommit)
    PairingCommitOrBuilder {
  private PairingCommit() {
    transcriptSignature_ = com.google.protobuf.ByteString.EMPTY;
    hostId_ = "";
    deviceId_ = "";
    sessionId_ = "";
  }
  public static final int TRANSCRIPT_SIGNATURE_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString transcriptSignature_;
  /**
   * <code>bytes transcript_signature = 1;</code>
   * @return The transcriptSignature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTranscriptSignature() {
    return transcriptSignature_;
  }
  /**
   * <code>bytes transcript_signature = 1;</code>
   * @param value The transcriptSignature to set.
   */
  private void setTranscriptSignature(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    transcriptSignature_ = value;
  }
  /**
   * <code>bytes transcript_signature = 1;</code>
   */
  private void clearTranscriptSignature() {

    transcriptSignature_ = getDefaultInstance().getTranscriptSignature();
  }

  public static final int HOST_ID_FIELD_NUMBER = 2;
  private java.lang.String hostId_;
  /**
   * <code>string host_id = 2;</code>
   * @return The hostId.
   */
  @java.lang.Override
  public java.lang.String getHostId() {
    return hostId_;
  }
  /**
   * <code>string host_id = 2;</code>
   * @return The bytes for hostId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(hostId_);
  }
  /**
   * <code>string host_id = 2;</code>
   * @param value The hostId to set.
   */
  private void setHostId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    hostId_ = value;
  }
  /**
   * <code>string host_id = 2;</code>
   */
  private void clearHostId() {

    hostId_ = getDefaultInstance().getHostId();
  }
  /**
   * <code>string host_id = 2;</code>
   * @param value The bytes for hostId to set.
   */
  private void setHostIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    hostId_ = value.toStringUtf8();

  }

  public static final int DEVICE_ID_FIELD_NUMBER = 3;
  private java.lang.String deviceId_;
  /**
   * <code>string device_id = 3;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    return deviceId_;
  }
  /**
   * <code>string device_id = 3;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
  }
  /**
   * <code>string device_id = 3;</code>
   * @param value The deviceId to set.
   */
  private void setDeviceId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    deviceId_ = value;
  }
  /**
   * <code>string device_id = 3;</code>
   */
  private void clearDeviceId() {

    deviceId_ = getDefaultInstance().getDeviceId();
  }
  /**
   * <code>string device_id = 3;</code>
   * @param value The bytes for deviceId to set.
   */
  private void setDeviceIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deviceId_ = value.toStringUtf8();

  }

  public static final int SESSION_ID_FIELD_NUMBER = 4;
  private java.lang.String sessionId_;
  /**
   * <code>string session_id = 4;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    return sessionId_;
  }
  /**
   * <code>string session_id = 4;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sessionId_);
  }
  /**
   * <code>string session_id = 4;</code>
   * @param value The sessionId to set.
   */
  private void setSessionId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    sessionId_ = value;
  }
  /**
   * <code>string session_id = 4;</code>
   */
  private void clearSessionId() {

    sessionId_ = getDefaultInstance().getSessionId();
  }
  /**
   * <code>string session_id = 4;</code>
   * @param value The bytes for sessionId to set.
   */
  private void setSessionIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    sessionId_ = value.toStringUtf8();

  }

  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.PairingCommit prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.PairingCommit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.PairingCommit, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.PairingCommit)
      com.xopmc.galaxybridge.protocol.v1.PairingCommitOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.PairingCommit.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bytes transcript_signature = 1;</code>
     * @return The transcriptSignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTranscriptSignature() {
      return instance.getTranscriptSignature();
    }
    /**
     * <code>bytes transcript_signature = 1;</code>
     * @param value The transcriptSignature to set.
     * @return This builder for chaining.
     */
    public Builder setTranscriptSignature(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTranscriptSignature(value);
      return this;
    }
    /**
     * <code>bytes transcript_signature = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTranscriptSignature() {
      copyOnWrite();
      instance.clearTranscriptSignature();
      return this;
    }

    /**
     * <code>string host_id = 2;</code>
     * @return The hostId.
     */
    @java.lang.Override
    public java.lang.String getHostId() {
      return instance.getHostId();
    }
    /**
     * <code>string host_id = 2;</code>
     * @return The bytes for hostId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostIdBytes() {
      return instance.getHostIdBytes();
    }
    /**
     * <code>string host_id = 2;</code>
     * @param value The hostId to set.
     * @return This builder for chaining.
     */
    public Builder setHostId(
        java.lang.String value) {
      copyOnWrite();
      instance.setHostId(value);
      return this;
    }
    /**
     * <code>string host_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostId() {
      copyOnWrite();
      instance.clearHostId();
      return this;
    }
    /**
     * <code>string host_id = 2;</code>
     * @param value The bytes for hostId to set.
     * @return This builder for chaining.
     */
    public Builder setHostIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setHostIdBytes(value);
      return this;
    }

    /**
     * <code>string device_id = 3;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <code>string device_id = 3;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return instance.getDeviceIdBytes();
    }
    /**
     * <code>string device_id = 3;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <code>string device_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }
    /**
     * <code>string device_id = 3;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceIdBytes(value);
      return this;
    }

    /**
     * <code>string session_id = 4;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public java.lang.String getSessionId() {
      return instance.getSessionId();
    }
    /**
     * <code>string session_id = 4;</code>
     * @return The bytes for sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      return instance.getSessionIdBytes();
    }
    /**
     * <code>string session_id = 4;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSessionId(value);
      return this;
    }
    /**
     * <code>string session_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      copyOnWrite();
      instance.clearSessionId();
      return this;
    }
    /**
     * <code>string session_id = 4;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSessionIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.PairingCommit)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.PairingCommit();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "transcriptSignature_",
            "hostId_",
            "deviceId_",
            "sessionId_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\n\u0002\u0208" +
              "\u0003\u0208\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.PairingCommit> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.PairingCommit.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.PairingCommit>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.PairingCommit)
  private static final com.xopmc.galaxybridge.protocol.v1.PairingCommit DEFAULT_INSTANCE;
  static {
    PairingCommit defaultInstance = new PairingCommit();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PairingCommit.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.PairingCommit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PairingCommit> PARSER;

  public static com.google.protobuf.Parser<PairingCommit> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

