// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface PairingCommitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.PairingCommit)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes transcript_signature = 1;</code>
   * @return The transcriptSignature.
   */
  com.google.protobuf.ByteString getTranscriptSignature();

  /**
   * <code>string host_id = 2;</code>
   * @return The hostId.
   */
  java.lang.String getHostId();
  /**
   * <code>string host_id = 2;</code>
   * @return The bytes for hostId.
   */
  com.google.protobuf.ByteString
      getHostIdBytes();

  /**
   * <code>string device_id = 3;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 3;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string session_id = 4;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 4;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
