// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface PairingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.PairingResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool accepted = 1;</code>
   * @return The accepted.
   */
  boolean getAccepted();

  /**
   * <code>bytes identity_public_key = 2;</code>
   * @return The identityPublicKey.
   */
  com.google.protobuf.ByteString getIdentityPublicKey();

  /**
   * <code>string rejection_reason = 3;</code>
   * @return The rejectionReason.
   */
  java.lang.String getRejectionReason();
  /**
   * <code>string rejection_reason = 3;</code>
   * @return The bytes for rejectionReason.
   */
  com.google.protobuf.ByteString
      getRejectionReasonBytes();

  /**
   * <code>bytes server_nonce = 4;</code>
   * @return The serverNonce.
   */
  com.google.protobuf.ByteString getServerNonce();

  /**
   * <code>bytes transcript_signature = 5;</code>
   * @return The transcriptSignature.
   */
  com.google.protobuf.ByteString getTranscriptSignature();

  /**
   * <code>bytes tls_certificate_sha256 = 6;</code>
   * @return The tlsCertificateSha256.
   */
  com.google.protobuf.ByteString getTlsCertificateSha256();

  /**
   * <code>string display_name = 7;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <code>string display_name = 7;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>string device_id = 8;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 8;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();
}
