// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface PairingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.PairingRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes one_time_token = 1;</code>
   * @return The oneTimeToken.
   */
  com.google.protobuf.ByteString getOneTimeToken();

  /**
   * <code>bytes identity_public_key = 2;</code>
   * @return The identityPublicKey.
   */
  com.google.protobuf.ByteString getIdentityPublicKey();

  /**
   * <code>string display_name = 3;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <code>string display_name = 3;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>bytes client_nonce = 4;</code>
   * @return The clientNonce.
   */
  com.google.protobuf.ByteString getClientNonce();

  /**
   * <code>bytes transcript_signature = 5;</code>
   * @return The transcriptSignature.
   */
  com.google.protobuf.ByteString getTranscriptSignature();
}
