// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.PairingRequest}
 */
@com.google.protobuf.Generated
public  final class PairingRequest extends
    com.google.protobuf.GeneratedMessageLite<
        PairingRequest, PairingRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.PairingRequest)
    PairingRequestOrBuilder {
  private PairingRequest() {
    oneTimeToken_ = com.google.protobuf.ByteString.EMPTY;
    identityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    displayName_ = "";
    clientNonce_ = com.google.protobuf.ByteString.EMPTY;
    transcriptSignature_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int ONE_TIME_TOKEN_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString oneTimeToken_;
  /**
   * <code>bytes one_time_token = 1;</code>
   * @return The oneTimeToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getOneTimeToken() {
    return oneTimeToken_;
  }
  /**
   * <code>bytes one_time_token = 1;</code>
   * @param value The oneTimeToken to set.
   */
  private void setOneTimeToken(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    oneTimeToken_ = value;
  }
  /**
   * <code>bytes one_time_token = 1;</code>
   */
  private void clearOneTimeToken() {

    oneTimeToken_ = getDefaultInstance().getOneTimeToken();
  }

  public static final int IDENTITY_PUBLIC_KEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString identityPublicKey_;
  /**
   * <code>bytes identity_public_key = 2;</code>
   * @return The identityPublicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIdentityPublicKey() {
    return identityPublicKey_;
  }
  /**
   * <code>bytes identity_public_key = 2;</code>
   * @param value The identityPublicKey to set.
   */
  private void setIdentityPublicKey(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    identityPublicKey_ = value;
  }
  /**
   * <code>bytes identity_public_key = 2;</code>
   */
  private void clearIdentityPublicKey() {

    identityPublicKey_ = getDefaultInstance().getIdentityPublicKey();
  }

  public static final int DISPLAY_NAME_FIELD_NUMBER = 3;
  private java.lang.String displayName_;
  /**
   * <code>string display_name = 3;</code>
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    return displayName_;
  }
  /**
   * <code>string display_name = 3;</code>
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(displayName_);
  }
  /**
   * <code>string display_name = 3;</code>
   * @param value The displayName to set.
   */
  private void setDisplayName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    displayName_ = value;
  }
  /**
   * <code>string display_name = 3;</code>
   */
  private void clearDisplayName() {

    displayName_ = getDefaultInstance().getDisplayName();
  }
  /**
   * <code>string display_name = 3;</code>
   * @param value The bytes for displayName to set.
   */
  private void setDisplayNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    displayName_ = value.toStringUtf8();

  }

  public static final int CLIENT_NONCE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString clientNonce_;
  /**
   * <code>bytes client_nonce = 4;</code>
   * @return The clientNonce.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getClientNonce() {
    return clientNonce_;
  }
  /**
   * <code>bytes client_nonce = 4;</code>
   * @param value The clientNonce to set.
   */
  private void setClientNonce(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    clientNonce_ = value;
  }
  /**
   * <code>bytes client_nonce = 4;</code>
   */
  private void clearClientNonce() {

    clientNonce_ = getDefaultInstance().getClientNonce();
  }

  public static final int TRANSCRIPT_SIGNATURE_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString transcriptSignature_;
  /**
   * <code>bytes transcript_signature = 5;</code>
   * @return The transcriptSignature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTranscriptSignature() {
    return transcriptSignature_;
  }
  /**
   * <code>bytes transcript_signature = 5;</code>
   * @param value The transcriptSignature to set.
   */
  private void setTranscriptSignature(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    transcriptSignature_ = value;
  }
  /**
   * <code>bytes transcript_signature = 5;</code>
   */
  private void clearTranscriptSignature() {

    transcriptSignature_ = getDefaultInstance().getTranscriptSignature();
  }

  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.PairingRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.PairingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.PairingRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.PairingRequest)
      com.xopmc.galaxybridge.protocol.v1.PairingRequestOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.PairingRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bytes one_time_token = 1;</code>
     * @return The oneTimeToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOneTimeToken() {
      return instance.getOneTimeToken();
    }
    /**
     * <code>bytes one_time_token = 1;</code>
     * @param value The oneTimeToken to set.
     * @return This builder for chaining.
     */
    public Builder setOneTimeToken(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOneTimeToken(value);
      return this;
    }
    /**
     * <code>bytes one_time_token = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOneTimeToken() {
      copyOnWrite();
      instance.clearOneTimeToken();
      return this;
    }

    /**
     * <code>bytes identity_public_key = 2;</code>
     * @return The identityPublicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIdentityPublicKey() {
      return instance.getIdentityPublicKey();
    }
    /**
     * <code>bytes identity_public_key = 2;</code>
     * @param value The identityPublicKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdentityPublicKey(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdentityPublicKey(value);
      return this;
    }
    /**
     * <code>bytes identity_public_key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentityPublicKey() {
      copyOnWrite();
      instance.clearIdentityPublicKey();
      return this;
    }

    /**
     * <code>string display_name = 3;</code>
     * @return The displayName.
     */
    @java.lang.Override
    public java.lang.String getDisplayName() {
      return instance.getDisplayName();
    }
    /**
     * <code>string display_name = 3;</code>
     * @return The bytes for displayName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      return instance.getDisplayNameBytes();
    }
    /**
     * <code>string display_name = 3;</code>
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(
        java.lang.String value) {
      copyOnWrite();
      instance.setDisplayName(value);
      return this;
    }
    /**
     * <code>string display_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      copyOnWrite();
      instance.clearDisplayName();
      return this;
    }
    /**
     * <code>string display_name = 3;</code>
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDisplayNameBytes(value);
      return this;
    }

    /**
     * <code>bytes client_nonce = 4;</code>
     * @return The clientNonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClientNonce() {
      return instance.getClientNonce();
    }
    /**
     * <code>bytes client_nonce = 4;</code>
     * @param value The clientNonce to set.
     * @return This builder for chaining.
     */
    public Builder setClientNonce(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientNonce(value);
      return this;
    }
    /**
     * <code>bytes client_nonce = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientNonce() {
      copyOnWrite();
      instance.clearClientNonce();
      return this;
    }

    /**
     * <code>bytes transcript_signature = 5;</code>
     * @return The transcriptSignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTranscriptSignature() {
      return instance.getTranscriptSignature();
    }
    /**
     * <code>bytes transcript_signature = 5;</code>
     * @param value The transcriptSignature to set.
     * @return This builder for chaining.
     */
    public Builder setTranscriptSignature(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTranscriptSignature(value);
      return this;
    }
    /**
     * <code>bytes transcript_signature = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTranscriptSignature() {
      copyOnWrite();
      instance.clearTranscriptSignature();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.PairingRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.PairingRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "oneTimeToken_",
            "identityPublicKey_",
            "displayName_",
            "clientNonce_",
            "transcriptSignature_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\n\u0002\n\u0003" +
              "\u0208\u0004\n\u0005\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.PairingRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.PairingRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.PairingRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.PairingRequest)
  private static final com.xopmc.galaxybridge.protocol.v1.PairingRequest DEFAULT_INSTANCE;
  static {
    PairingRequest defaultInstance = new PairingRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PairingRequest.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.PairingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PairingRequest> PARSER;

  public static com.google.protobuf.Parser<PairingRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

