// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface PingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.Ping)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint64 monotonic_time_ns = 1;</code>
   * @return The monotonicTimeNs.
   */
  long getMonotonicTimeNs();
}
