// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.Pong}
 */
@com.google.protobuf.Generated
public  final class Pong extends
    com.google.protobuf.GeneratedMessageLite<
        Pong, Pong.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.Pong)
    PongOrBuilder {
  private Pong() {
  }
  public static final int ECHOED_MONOTONIC_TIME_NS_FIELD_NUMBER = 1;
  private long echoedMonotonicTimeNs_;
  /**
   * <code>uint64 echoed_monotonic_time_ns = 1;</code>
   * @return The echoedMonotonicTimeNs.
   */
  @java.lang.Override
  public long getEchoedMonotonicTimeNs() {
    return echoedMonotonicTimeNs_;
  }
  /**
   * <code>uint64 echoed_monotonic_time_ns = 1;</code>
   * @param value The echoedMonotonicTimeNs to set.
   */
  private void setEchoedMonotonicTimeNs(long value) {
    
    echoedMonotonicTimeNs_ = value;
  }
  /**
   * <code>uint64 echoed_monotonic_time_ns = 1;</code>
   */
  private void clearEchoedMonotonicTimeNs() {

    echoedMonotonicTimeNs_ = 0L;
  }

  public static com.xopmc.galaxybridge.protocol.v1.Pong parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Pong parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Pong parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Pong parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Pong parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Pong parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Pong parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Pong parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.Pong parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.Pong parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Pong parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.Pong parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.Pong prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.Pong}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.Pong, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.Pong)
      com.xopmc.galaxybridge.protocol.v1.PongOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.Pong.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint64 echoed_monotonic_time_ns = 1;</code>
     * @return The echoedMonotonicTimeNs.
     */
    @java.lang.Override
    public long getEchoedMonotonicTimeNs() {
      return instance.getEchoedMonotonicTimeNs();
    }
    /**
     * <code>uint64 echoed_monotonic_time_ns = 1;</code>
     * @param value The echoedMonotonicTimeNs to set.
     * @return This builder for chaining.
     */
    public Builder setEchoedMonotonicTimeNs(long value) {
      copyOnWrite();
      instance.setEchoedMonotonicTimeNs(value);
      return this;
    }
    /**
     * <code>uint64 echoed_monotonic_time_ns = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEchoedMonotonicTimeNs() {
      copyOnWrite();
      instance.clearEchoedMonotonicTimeNs();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.Pong)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.Pong();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "echoedMonotonicTimeNs_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0003";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.Pong> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.Pong.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.Pong>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.Pong)
  private static final com.xopmc.galaxybridge.protocol.v1.Pong DEFAULT_INSTANCE;
  static {
    Pong defaultInstance = new Pong();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Pong.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.Pong getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Pong> PARSER;

  public static com.google.protobuf.Parser<Pong> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

