// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface PongOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.Pong)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint64 echoed_monotonic_time_ns = 1;</code>
   * @return The echoedMonotonicTimeNs.
   */
  long getEchoedMonotonicTimeNs();
}
