// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.SessionAuthentication}
 */
@com.google.protobuf.Generated
public  final class SessionAuthentication extends
    com.google.protobuf.GeneratedMessageLite<
        SessionAuthentication, SessionAuthentication.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.SessionAuthentication)
    SessionAuthenticationOrBuilder {
  private SessionAuthentication() {
    identityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    nonce_ = com.google.protobuf.ByteString.EMPTY;
    signature_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int IDENTITY_PUBLIC_KEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString identityPublicKey_;
  /**
   * <code>bytes identity_public_key = 1;</code>
   * @return The identityPublicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIdentityPublicKey() {
    return identityPublicKey_;
  }
  /**
   * <code>bytes identity_public_key = 1;</code>
   * @param value The identityPublicKey to set.
   */
  private void setIdentityPublicKey(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    identityPublicKey_ = value;
  }
  /**
   * <code>bytes identity_public_key = 1;</code>
   */
  private void clearIdentityPublicKey() {

    identityPublicKey_ = getDefaultInstance().getIdentityPublicKey();
  }

  public static final int NONCE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString nonce_;
  /**
   * <code>bytes nonce = 2;</code>
   * @return The nonce.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNonce() {
    return nonce_;
  }
  /**
   * <code>bytes nonce = 2;</code>
   * @param value The nonce to set.
   */
  private void setNonce(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    nonce_ = value;
  }
  /**
   * <code>bytes nonce = 2;</code>
   */
  private void clearNonce() {

    nonce_ = getDefaultInstance().getNonce();
  }

  public static final int TIMESTAMP_UNIX_SECONDS_FIELD_NUMBER = 3;
  private long timestampUnixSeconds_;
  /**
   * <code>int64 timestamp_unix_seconds = 3;</code>
   * @return The timestampUnixSeconds.
   */
  @java.lang.Override
  public long getTimestampUnixSeconds() {
    return timestampUnixSeconds_;
  }
  /**
   * <code>int64 timestamp_unix_seconds = 3;</code>
   * @param value The timestampUnixSeconds to set.
   */
  private void setTimestampUnixSeconds(long value) {
    
    timestampUnixSeconds_ = value;
  }
  /**
   * <code>int64 timestamp_unix_seconds = 3;</code>
   */
  private void clearTimestampUnixSeconds() {

    timestampUnixSeconds_ = 0L;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString signature_;
  /**
   * <code>bytes signature = 4;</code>
   * @return The signature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSignature() {
    return signature_;
  }
  /**
   * <code>bytes signature = 4;</code>
   * @param value The signature to set.
   */
  private void setSignature(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    signature_ = value;
  }
  /**
   * <code>bytes signature = 4;</code>
   */
  private void clearSignature() {

    signature_ = getDefaultInstance().getSignature();
  }

  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.SessionAuthentication prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.SessionAuthentication}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.SessionAuthentication, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.SessionAuthentication)
      com.xopmc.galaxybridge.protocol.v1.SessionAuthenticationOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.SessionAuthentication.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bytes identity_public_key = 1;</code>
     * @return The identityPublicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIdentityPublicKey() {
      return instance.getIdentityPublicKey();
    }
    /**
     * <code>bytes identity_public_key = 1;</code>
     * @param value The identityPublicKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdentityPublicKey(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdentityPublicKey(value);
      return this;
    }
    /**
     * <code>bytes identity_public_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentityPublicKey() {
      copyOnWrite();
      instance.clearIdentityPublicKey();
      return this;
    }

    /**
     * <code>bytes nonce = 2;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNonce() {
      return instance.getNonce();
    }
    /**
     * <code>bytes nonce = 2;</code>
     * @param value The nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonce(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNonce(value);
      return this;
    }
    /**
     * <code>bytes nonce = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonce() {
      copyOnWrite();
      instance.clearNonce();
      return this;
    }

    /**
     * <code>int64 timestamp_unix_seconds = 3;</code>
     * @return The timestampUnixSeconds.
     */
    @java.lang.Override
    public long getTimestampUnixSeconds() {
      return instance.getTimestampUnixSeconds();
    }
    /**
     * <code>int64 timestamp_unix_seconds = 3;</code>
     * @param value The timestampUnixSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampUnixSeconds(long value) {
      copyOnWrite();
      instance.setTimestampUnixSeconds(value);
      return this;
    }
    /**
     * <code>int64 timestamp_unix_seconds = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampUnixSeconds() {
      copyOnWrite();
      instance.clearTimestampUnixSeconds();
      return this;
    }

    /**
     * <code>bytes signature = 4;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return instance.getSignature();
    }
    /**
     * <code>bytes signature = 4;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSignature(value);
      return this;
    }
    /**
     * <code>bytes signature = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      copyOnWrite();
      instance.clearSignature();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.SessionAuthentication)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.SessionAuthentication();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "identityPublicKey_",
            "nonce_",
            "timestampUnixSeconds_",
            "signature_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\n\u0002\n\u0003" +
              "\u0002\u0004\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.SessionAuthentication> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.SessionAuthentication.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.SessionAuthentication>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.SessionAuthentication)
  private static final com.xopmc.galaxybridge.protocol.v1.SessionAuthentication DEFAULT_INSTANCE;
  static {
    SessionAuthentication defaultInstance = new SessionAuthentication();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SessionAuthentication.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.SessionAuthentication getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SessionAuthentication> PARSER;

  public static com.google.protobuf.Parser<SessionAuthentication> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

