// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface SessionAuthenticationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.SessionAuthentication)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes identity_public_key = 1;</code>
   * @return The identityPublicKey.
   */
  com.google.protobuf.ByteString getIdentityPublicKey();

  /**
   * <code>bytes nonce = 2;</code>
   * @return The nonce.
   */
  com.google.protobuf.ByteString getNonce();

  /**
   * <code>int64 timestamp_unix_seconds = 3;</code>
   * @return The timestampUnixSeconds.
   */
  long getTimestampUnixSeconds();

  /**
   * <code>bytes signature = 4;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
