// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.SmsEvent}
 */
@com.google.protobuf.Generated
public  final class SmsEvent extends
    com.google.protobuf.GeneratedMessageLite<
        SmsEvent, SmsEvent.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.SmsEvent)
    SmsEventOrBuilder {
  private SmsEvent() {
    messageId_ = "";
    threadId_ = "";
    address_ = "";
    body_ = "";
  }
  public static final int MESSAGE_ID_FIELD_NUMBER = 1;
  private java.lang.String messageId_;
  /**
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    return messageId_;
  }
  /**
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(messageId_);
  }
  /**
   * <code>string message_id = 1;</code>
   * @param value The messageId to set.
   */
  private void setMessageId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    messageId_ = value;
  }
  /**
   * <code>string message_id = 1;</code>
   */
  private void clearMessageId() {

    messageId_ = getDefaultInstance().getMessageId();
  }
  /**
   * <code>string message_id = 1;</code>
   * @param value The bytes for messageId to set.
   */
  private void setMessageIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    messageId_ = value.toStringUtf8();

  }

  public static final int THREAD_ID_FIELD_NUMBER = 2;
  private java.lang.String threadId_;
  /**
   * <code>string thread_id = 2;</code>
   * @return The threadId.
   */
  @java.lang.Override
  public java.lang.String getThreadId() {
    return threadId_;
  }
  /**
   * <code>string thread_id = 2;</code>
   * @return The bytes for threadId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThreadIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(threadId_);
  }
  /**
   * <code>string thread_id = 2;</code>
   * @param value The threadId to set.
   */
  private void setThreadId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    threadId_ = value;
  }
  /**
   * <code>string thread_id = 2;</code>
   */
  private void clearThreadId() {

    threadId_ = getDefaultInstance().getThreadId();
  }
  /**
   * <code>string thread_id = 2;</code>
   * @param value The bytes for threadId to set.
   */
  private void setThreadIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    threadId_ = value.toStringUtf8();

  }

  public static final int ADDRESS_FIELD_NUMBER = 3;
  private java.lang.String address_;
  /**
   * <code>string address = 3;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    return address_;
  }
  /**
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(address_);
  }
  /**
   * <code>string address = 3;</code>
   * @param value The address to set.
   */
  private void setAddress(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    address_ = value;
  }
  /**
   * <code>string address = 3;</code>
   */
  private void clearAddress() {

    address_ = getDefaultInstance().getAddress();
  }
  /**
   * <code>string address = 3;</code>
   * @param value The bytes for address to set.
   */
  private void setAddressBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    address_ = value.toStringUtf8();

  }

  public static final int BODY_FIELD_NUMBER = 4;
  private java.lang.String body_;
  /**
   * <code>string body = 4;</code>
   * @return The body.
   */
  @java.lang.Override
  public java.lang.String getBody() {
    return body_;
  }
  /**
   * <code>string body = 4;</code>
   * @return The bytes for body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBodyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(body_);
  }
  /**
   * <code>string body = 4;</code>
   * @param value The body to set.
   */
  private void setBody(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    body_ = value;
  }
  /**
   * <code>string body = 4;</code>
   */
  private void clearBody() {

    body_ = getDefaultInstance().getBody();
  }
  /**
   * <code>string body = 4;</code>
   * @param value The bytes for body to set.
   */
  private void setBodyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    body_ = value.toStringUtf8();

  }

  public static final int TIMESTAMP_UNIX_MS_FIELD_NUMBER = 5;
  private long timestampUnixMs_;
  /**
   * <code>int64 timestamp_unix_ms = 5;</code>
   * @return The timestampUnixMs.
   */
  @java.lang.Override
  public long getTimestampUnixMs() {
    return timestampUnixMs_;
  }
  /**
   * <code>int64 timestamp_unix_ms = 5;</code>
   * @param value The timestampUnixMs to set.
   */
  private void setTimestampUnixMs(long value) {
    
    timestampUnixMs_ = value;
  }
  /**
   * <code>int64 timestamp_unix_ms = 5;</code>
   */
  private void clearTimestampUnixMs() {

    timestampUnixMs_ = 0L;
  }

  public static final int OUTGOING_FIELD_NUMBER = 6;
  private boolean outgoing_;
  /**
   * <code>bool outgoing = 6;</code>
   * @return The outgoing.
   */
  @java.lang.Override
  public boolean getOutgoing() {
    return outgoing_;
  }
  /**
   * <code>bool outgoing = 6;</code>
   * @param value The outgoing to set.
   */
  private void setOutgoing(boolean value) {
    
    outgoing_ = value;
  }
  /**
   * <code>bool outgoing = 6;</code>
   */
  private void clearOutgoing() {

    outgoing_ = false;
  }

  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.SmsEvent prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.SmsEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.SmsEvent, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.SmsEvent)
      com.xopmc.galaxybridge.protocol.v1.SmsEventOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.SmsEvent.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string message_id = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public java.lang.String getMessageId() {
      return instance.getMessageId();
    }
    /**
     * <code>string message_id = 1;</code>
     * @return The bytes for messageId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      return instance.getMessageIdBytes();
    }
    /**
     * <code>string message_id = 1;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessageId(value);
      return this;
    }
    /**
     * <code>string message_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      copyOnWrite();
      instance.clearMessageId();
      return this;
    }
    /**
     * <code>string message_id = 1;</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageIdBytes(value);
      return this;
    }

    /**
     * <code>string thread_id = 2;</code>
     * @return The threadId.
     */
    @java.lang.Override
    public java.lang.String getThreadId() {
      return instance.getThreadId();
    }
    /**
     * <code>string thread_id = 2;</code>
     * @return The bytes for threadId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getThreadIdBytes() {
      return instance.getThreadIdBytes();
    }
    /**
     * <code>string thread_id = 2;</code>
     * @param value The threadId to set.
     * @return This builder for chaining.
     */
    public Builder setThreadId(
        java.lang.String value) {
      copyOnWrite();
      instance.setThreadId(value);
      return this;
    }
    /**
     * <code>string thread_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearThreadId() {
      copyOnWrite();
      instance.clearThreadId();
      return this;
    }
    /**
     * <code>string thread_id = 2;</code>
     * @param value The bytes for threadId to set.
     * @return This builder for chaining.
     */
    public Builder setThreadIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setThreadIdBytes(value);
      return this;
    }

    /**
     * <code>string address = 3;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      return instance.getAddress();
    }
    /**
     * <code>string address = 3;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      return instance.getAddressBytes();
    }
    /**
     * <code>string address = 3;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      copyOnWrite();
      instance.setAddress(value);
      return this;
    }
    /**
     * <code>string address = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      copyOnWrite();
      instance.clearAddress();
      return this;
    }
    /**
     * <code>string address = 3;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAddressBytes(value);
      return this;
    }

    /**
     * <code>string body = 4;</code>
     * @return The body.
     */
    @java.lang.Override
    public java.lang.String getBody() {
      return instance.getBody();
    }
    /**
     * <code>string body = 4;</code>
     * @return The bytes for body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBodyBytes() {
      return instance.getBodyBytes();
    }
    /**
     * <code>string body = 4;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(
        java.lang.String value) {
      copyOnWrite();
      instance.setBody(value);
      return this;
    }
    /**
     * <code>string body = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      copyOnWrite();
      instance.clearBody();
      return this;
    }
    /**
     * <code>string body = 4;</code>
     * @param value The bytes for body to set.
     * @return This builder for chaining.
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBodyBytes(value);
      return this;
    }

    /**
     * <code>int64 timestamp_unix_ms = 5;</code>
     * @return The timestampUnixMs.
     */
    @java.lang.Override
    public long getTimestampUnixMs() {
      return instance.getTimestampUnixMs();
    }
    /**
     * <code>int64 timestamp_unix_ms = 5;</code>
     * @param value The timestampUnixMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampUnixMs(long value) {
      copyOnWrite();
      instance.setTimestampUnixMs(value);
      return this;
    }
    /**
     * <code>int64 timestamp_unix_ms = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampUnixMs() {
      copyOnWrite();
      instance.clearTimestampUnixMs();
      return this;
    }

    /**
     * <code>bool outgoing = 6;</code>
     * @return The outgoing.
     */
    @java.lang.Override
    public boolean getOutgoing() {
      return instance.getOutgoing();
    }
    /**
     * <code>bool outgoing = 6;</code>
     * @param value The outgoing to set.
     * @return This builder for chaining.
     */
    public Builder setOutgoing(boolean value) {
      copyOnWrite();
      instance.setOutgoing(value);
      return this;
    }
    /**
     * <code>bool outgoing = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutgoing() {
      copyOnWrite();
      instance.clearOutgoing();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.SmsEvent)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.SmsEvent();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "messageId_",
            "threadId_",
            "address_",
            "body_",
            "timestampUnixMs_",
            "outgoing_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\u0002\u0006\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.SmsEvent> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.SmsEvent.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.SmsEvent>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.SmsEvent)
  private static final com.xopmc.galaxybridge.protocol.v1.SmsEvent DEFAULT_INSTANCE;
  static {
    SmsEvent defaultInstance = new SmsEvent();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SmsEvent.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.SmsEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SmsEvent> PARSER;

  public static com.google.protobuf.Parser<SmsEvent> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

