// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface SmsEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.SmsEvent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>string thread_id = 2;</code>
   * @return The threadId.
   */
  java.lang.String getThreadId();
  /**
   * <code>string thread_id = 2;</code>
   * @return The bytes for threadId.
   */
  com.google.protobuf.ByteString
      getThreadIdBytes();

  /**
   * <code>string address = 3;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string body = 4;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 4;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>int64 timestamp_unix_ms = 5;</code>
   * @return The timestampUnixMs.
   */
  long getTimestampUnixMs();

  /**
   * <code>bool outgoing = 6;</code>
   * @return The outgoing.
   */
  boolean getOutgoing();
}
