// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.TransferManifest}
 */
@com.google.protobuf.Generated
public  final class TransferManifest extends
    com.google.protobuf.GeneratedMessageLite<
        TransferManifest, TransferManifest.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.TransferManifest)
    TransferManifestOrBuilder {
  private TransferManifest() {
    transferId_ = "";
    relativeName_ = "";
    mimeType_ = "";
    sha256_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int TRANSFER_ID_FIELD_NUMBER = 1;
  private java.lang.String transferId_;
  /**
   * <code>string transfer_id = 1;</code>
   * @return The transferId.
   */
  @java.lang.Override
  public java.lang.String getTransferId() {
    return transferId_;
  }
  /**
   * <code>string transfer_id = 1;</code>
   * @return The bytes for transferId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransferIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(transferId_);
  }
  /**
   * <code>string transfer_id = 1;</code>
   * @param value The transferId to set.
   */
  private void setTransferId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    transferId_ = value;
  }
  /**
   * <code>string transfer_id = 1;</code>
   */
  private void clearTransferId() {

    transferId_ = getDefaultInstance().getTransferId();
  }
  /**
   * <code>string transfer_id = 1;</code>
   * @param value The bytes for transferId to set.
   */
  private void setTransferIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    transferId_ = value.toStringUtf8();

  }

  public static final int RELATIVE_NAME_FIELD_NUMBER = 2;
  private java.lang.String relativeName_;
  /**
   * <code>string relative_name = 2;</code>
   * @return The relativeName.
   */
  @java.lang.Override
  public java.lang.String getRelativeName() {
    return relativeName_;
  }
  /**
   * <code>string relative_name = 2;</code>
   * @return The bytes for relativeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRelativeNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(relativeName_);
  }
  /**
   * <code>string relative_name = 2;</code>
   * @param value The relativeName to set.
   */
  private void setRelativeName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    relativeName_ = value;
  }
  /**
   * <code>string relative_name = 2;</code>
   */
  private void clearRelativeName() {

    relativeName_ = getDefaultInstance().getRelativeName();
  }
  /**
   * <code>string relative_name = 2;</code>
   * @param value The bytes for relativeName to set.
   */
  private void setRelativeNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    relativeName_ = value.toStringUtf8();

  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private long size_;
  /**
   * <code>uint64 size = 3;</code>
   * @return The size.
   */
  @java.lang.Override
  public long getSize() {
    return size_;
  }
  /**
   * <code>uint64 size = 3;</code>
   * @param value The size to set.
   */
  private void setSize(long value) {
    
    size_ = value;
  }
  /**
   * <code>uint64 size = 3;</code>
   */
  private void clearSize() {

    size_ = 0L;
  }

  public static final int MIME_TYPE_FIELD_NUMBER = 4;
  private java.lang.String mimeType_;
  /**
   * <code>string mime_type = 4;</code>
   * @return The mimeType.
   */
  @java.lang.Override
  public java.lang.String getMimeType() {
    return mimeType_;
  }
  /**
   * <code>string mime_type = 4;</code>
   * @return The bytes for mimeType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMimeTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mimeType_);
  }
  /**
   * <code>string mime_type = 4;</code>
   * @param value The mimeType to set.
   */
  private void setMimeType(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    mimeType_ = value;
  }
  /**
   * <code>string mime_type = 4;</code>
   */
  private void clearMimeType() {

    mimeType_ = getDefaultInstance().getMimeType();
  }
  /**
   * <code>string mime_type = 4;</code>
   * @param value The bytes for mimeType to set.
   */
  private void setMimeTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    mimeType_ = value.toStringUtf8();

  }

  public static final int SHA256_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString sha256_;
  /**
   * <code>bytes sha256 = 5;</code>
   * @return The sha256.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSha256() {
    return sha256_;
  }
  /**
   * <code>bytes sha256 = 5;</code>
   * @param value The sha256 to set.
   */
  private void setSha256(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    sha256_ = value;
  }
  /**
   * <code>bytes sha256 = 5;</code>
   */
  private void clearSha256() {

    sha256_ = getDefaultInstance().getSha256();
  }

  public static final int CONFIRMED_OFFSET_FIELD_NUMBER = 6;
  private long confirmedOffset_;
  /**
   * <code>uint64 confirmed_offset = 6;</code>
   * @return The confirmedOffset.
   */
  @java.lang.Override
  public long getConfirmedOffset() {
    return confirmedOffset_;
  }
  /**
   * <code>uint64 confirmed_offset = 6;</code>
   * @param value The confirmedOffset to set.
   */
  private void setConfirmedOffset(long value) {
    
    confirmedOffset_ = value;
  }
  /**
   * <code>uint64 confirmed_offset = 6;</code>
   */
  private void clearConfirmedOffset() {

    confirmedOffset_ = 0L;
  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.TransferManifest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.TransferManifest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.TransferManifest, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.TransferManifest)
      com.xopmc.galaxybridge.protocol.v1.TransferManifestOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.TransferManifest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string transfer_id = 1;</code>
     * @return The transferId.
     */
    @java.lang.Override
    public java.lang.String getTransferId() {
      return instance.getTransferId();
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @return The bytes for transferId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTransferIdBytes() {
      return instance.getTransferIdBytes();
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @param value The transferId to set.
     * @return This builder for chaining.
     */
    public Builder setTransferId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTransferId(value);
      return this;
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransferId() {
      copyOnWrite();
      instance.clearTransferId();
      return this;
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @param value The bytes for transferId to set.
     * @return This builder for chaining.
     */
    public Builder setTransferIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTransferIdBytes(value);
      return this;
    }

    /**
     * <code>string relative_name = 2;</code>
     * @return The relativeName.
     */
    @java.lang.Override
    public java.lang.String getRelativeName() {
      return instance.getRelativeName();
    }
    /**
     * <code>string relative_name = 2;</code>
     * @return The bytes for relativeName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRelativeNameBytes() {
      return instance.getRelativeNameBytes();
    }
    /**
     * <code>string relative_name = 2;</code>
     * @param value The relativeName to set.
     * @return This builder for chaining.
     */
    public Builder setRelativeName(
        java.lang.String value) {
      copyOnWrite();
      instance.setRelativeName(value);
      return this;
    }
    /**
     * <code>string relative_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRelativeName() {
      copyOnWrite();
      instance.clearRelativeName();
      return this;
    }
    /**
     * <code>string relative_name = 2;</code>
     * @param value The bytes for relativeName to set.
     * @return This builder for chaining.
     */
    public Builder setRelativeNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRelativeNameBytes(value);
      return this;
    }

    /**
     * <code>uint64 size = 3;</code>
     * @return The size.
     */
    @java.lang.Override
    public long getSize() {
      return instance.getSize();
    }
    /**
     * <code>uint64 size = 3;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(long value) {
      copyOnWrite();
      instance.setSize(value);
      return this;
    }
    /**
     * <code>uint64 size = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      copyOnWrite();
      instance.clearSize();
      return this;
    }

    /**
     * <code>string mime_type = 4;</code>
     * @return The mimeType.
     */
    @java.lang.Override
    public java.lang.String getMimeType() {
      return instance.getMimeType();
    }
    /**
     * <code>string mime_type = 4;</code>
     * @return The bytes for mimeType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      return instance.getMimeTypeBytes();
    }
    /**
     * <code>string mime_type = 4;</code>
     * @param value The mimeType to set.
     * @return This builder for chaining.
     */
    public Builder setMimeType(
        java.lang.String value) {
      copyOnWrite();
      instance.setMimeType(value);
      return this;
    }
    /**
     * <code>string mime_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMimeType() {
      copyOnWrite();
      instance.clearMimeType();
      return this;
    }
    /**
     * <code>string mime_type = 4;</code>
     * @param value The bytes for mimeType to set.
     * @return This builder for chaining.
     */
    public Builder setMimeTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMimeTypeBytes(value);
      return this;
    }

    /**
     * <code>bytes sha256 = 5;</code>
     * @return The sha256.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSha256() {
      return instance.getSha256();
    }
    /**
     * <code>bytes sha256 = 5;</code>
     * @param value The sha256 to set.
     * @return This builder for chaining.
     */
    public Builder setSha256(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSha256(value);
      return this;
    }
    /**
     * <code>bytes sha256 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSha256() {
      copyOnWrite();
      instance.clearSha256();
      return this;
    }

    /**
     * <code>uint64 confirmed_offset = 6;</code>
     * @return The confirmedOffset.
     */
    @java.lang.Override
    public long getConfirmedOffset() {
      return instance.getConfirmedOffset();
    }
    /**
     * <code>uint64 confirmed_offset = 6;</code>
     * @param value The confirmedOffset to set.
     * @return This builder for chaining.
     */
    public Builder setConfirmedOffset(long value) {
      copyOnWrite();
      instance.setConfirmedOffset(value);
      return this;
    }
    /**
     * <code>uint64 confirmed_offset = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfirmedOffset() {
      copyOnWrite();
      instance.clearConfirmedOffset();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.TransferManifest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.TransferManifest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "transferId_",
            "relativeName_",
            "size_",
            "mimeType_",
            "sha256_",
            "confirmedOffset_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0003\u0004\u0208\u0005\n\u0006\u0003";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.TransferManifest> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.TransferManifest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.TransferManifest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.TransferManifest)
  private static final com.xopmc.galaxybridge.protocol.v1.TransferManifest DEFAULT_INSTANCE;
  static {
    TransferManifest defaultInstance = new TransferManifest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TransferManifest.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferManifest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TransferManifest> PARSER;

  public static com.google.protobuf.Parser<TransferManifest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

