// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf enum {@code galaxybridge.v1.TransportKind}
 */
@com.google.protobuf.Generated
public enum TransportKind
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>TRANSPORT_KIND_UNSPECIFIED = 0;</code>
   */
  TRANSPORT_KIND_UNSPECIFIED(0),
  /**
   * <code>TRANSPORT_KIND_USB_ADB = 1;</code>
   */
  TRANSPORT_KIND_USB_ADB(1),
  /**
   * <code>TRANSPORT_KIND_WIRELESS_ADB = 2;</code>
   */
  TRANSPORT_KIND_WIRELESS_ADB(2),
  /**
   * <code>TRANSPORT_KIND_COMPANION_LAN = 3;</code>
   */
  TRANSPORT_KIND_COMPANION_LAN(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TRANSPORT_KIND_UNSPECIFIED = 0;</code>
   */
  public static final int TRANSPORT_KIND_UNSPECIFIED_VALUE = 0;
  /**
   * <code>TRANSPORT_KIND_USB_ADB = 1;</code>
   */
  public static final int TRANSPORT_KIND_USB_ADB_VALUE = 1;
  /**
   * <code>TRANSPORT_KIND_WIRELESS_ADB = 2;</code>
   */
  public static final int TRANSPORT_KIND_WIRELESS_ADB_VALUE = 2;
  /**
   * <code>TRANSPORT_KIND_COMPANION_LAN = 3;</code>
   */
  public static final int TRANSPORT_KIND_COMPANION_LAN_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TransportKind valueOf(int value) {
    return forNumber(value);
  }

  public static TransportKind forNumber(int value) {
    switch (value) {
      case 0: return TRANSPORT_KIND_UNSPECIFIED;
      case 1: return TRANSPORT_KIND_USB_ADB;
      case 2: return TRANSPORT_KIND_WIRELESS_ADB;
      case 3: return TRANSPORT_KIND_COMPANION_LAN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TransportKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TransportKind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TransportKind>() {
          @java.lang.Override
          public TransportKind findValueByNumber(int number) {
            return TransportKind.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return TransportKindVerifier.INSTANCE;
  }

  private static final class TransportKindVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new TransportKindVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return TransportKind.forNumber(number) != null;
          }
        };

  private final int value;

  private TransportKind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:galaxybridge.v1.TransportKind)
}

