// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface TransferCancelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.TransferCancel)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string transfer_id = 1;</code>
   * @return The transferId.
   */
  java.lang.String getTransferId();
  /**
   * <code>string transfer_id = 1;</code>
   * @return The bytes for transferId.
   */
  com.google.protobuf.ByteString
      getTransferIdBytes();
}
