// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

@com.google.protobuf.Generated
public interface TransferManifestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:galaxybridge.v1.TransferManifest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string transfer_id = 1;</code>
   * @return The transferId.
   */
  java.lang.String getTransferId();
  /**
   * <code>string transfer_id = 1;</code>
   * @return The bytes for transferId.
   */
  com.google.protobuf.ByteString
      getTransferIdBytes();

  /**
   * <code>string relative_name = 2;</code>
   * @return The relativeName.
   */
  java.lang.String getRelativeName();
  /**
   * <code>string relative_name = 2;</code>
   * @return The bytes for relativeName.
   */
  com.google.protobuf.ByteString
      getRelativeNameBytes();

  /**
   * <code>uint64 size = 3;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>string mime_type = 4;</code>
   * @return The mimeType.
   */
  java.lang.String getMimeType();
  /**
   * <code>string mime_type = 4;</code>
   * @return The bytes for mimeType.
   */
  com.google.protobuf.ByteString
      getMimeTypeBytes();

  /**
   * <code>bytes sha256 = 5;</code>
   * @return The sha256.
   */
  com.google.protobuf.ByteString getSha256();

  /**
   * <code>uint64 confirmed_offset = 6;</code>
   * @return The confirmedOffset.
   */
  long getConfirmedOffset();
}
