// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * Protobuf type {@code galaxybridge.v1.TransferAck}
 */
@com.google.protobuf.Generated
public  final class TransferAck extends
    com.google.protobuf.GeneratedMessageLite<
        TransferAck, TransferAck.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.TransferAck)
    TransferAckOrBuilder {
  private TransferAck() {
    transferId_ = "";
    failureReason_ = "";
    publishedName_ = "";
  }
  public static final int TRANSFER_ID_FIELD_NUMBER = 1;
  private java.lang.String transferId_;
  /**
   * <code>string transfer_id = 1;</code>
   * @return The transferId.
   */
  @java.lang.Override
  public java.lang.String getTransferId() {
    return transferId_;
  }
  /**
   * <code>string transfer_id = 1;</code>
   * @return The bytes for transferId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransferIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(transferId_);
  }
  /**
   * <code>string transfer_id = 1;</code>
   * @param value The transferId to set.
   */
  private void setTransferId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    transferId_ = value;
  }
  /**
   * <code>string transfer_id = 1;</code>
   */
  private void clearTransferId() {

    transferId_ = getDefaultInstance().getTransferId();
  }
  /**
   * <code>string transfer_id = 1;</code>
   * @param value The bytes for transferId to set.
   */
  private void setTransferIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    transferId_ = value.toStringUtf8();

  }

  public static final int CONFIRMED_OFFSET_FIELD_NUMBER = 2;
  private long confirmedOffset_;
  /**
   * <code>uint64 confirmed_offset = 2;</code>
   * @return The confirmedOffset.
   */
  @java.lang.Override
  public long getConfirmedOffset() {
    return confirmedOffset_;
  }
  /**
   * <code>uint64 confirmed_offset = 2;</code>
   * @param value The confirmedOffset to set.
   */
  private void setConfirmedOffset(long value) {
    
    confirmedOffset_ = value;
  }
  /**
   * <code>uint64 confirmed_offset = 2;</code>
   */
  private void clearConfirmedOffset() {

    confirmedOffset_ = 0L;
  }

  public static final int COMPLETE_FIELD_NUMBER = 3;
  private boolean complete_;
  /**
   * <code>bool complete = 3;</code>
   * @return The complete.
   */
  @java.lang.Override
  public boolean getComplete() {
    return complete_;
  }
  /**
   * <code>bool complete = 3;</code>
   * @param value The complete to set.
   */
  private void setComplete(boolean value) {
    
    complete_ = value;
  }
  /**
   * <code>bool complete = 3;</code>
   */
  private void clearComplete() {

    complete_ = false;
  }

  public static final int FAILURE_REASON_FIELD_NUMBER = 4;
  private java.lang.String failureReason_;
  /**
   * <code>string failure_reason = 4;</code>
   * @return The failureReason.
   */
  @java.lang.Override
  public java.lang.String getFailureReason() {
    return failureReason_;
  }
  /**
   * <code>string failure_reason = 4;</code>
   * @return The bytes for failureReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFailureReasonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(failureReason_);
  }
  /**
   * <code>string failure_reason = 4;</code>
   * @param value The failureReason to set.
   */
  private void setFailureReason(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    failureReason_ = value;
  }
  /**
   * <code>string failure_reason = 4;</code>
   */
  private void clearFailureReason() {

    failureReason_ = getDefaultInstance().getFailureReason();
  }
  /**
   * <code>string failure_reason = 4;</code>
   * @param value The bytes for failureReason to set.
   */
  private void setFailureReasonBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    failureReason_ = value.toStringUtf8();

  }

  public static final int PUBLISHED_NAME_FIELD_NUMBER = 5;
  private java.lang.String publishedName_;
  /**
   * <pre>
   * Actual provider-selected name, present only in a durable completion receipt.
   * </pre>
   *
   * <code>string published_name = 5;</code>
   * @return The publishedName.
   */
  @java.lang.Override
  public java.lang.String getPublishedName() {
    return publishedName_;
  }
  /**
   * <pre>
   * Actual provider-selected name, present only in a durable completion receipt.
   * </pre>
   *
   * <code>string published_name = 5;</code>
   * @return The bytes for publishedName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPublishedNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(publishedName_);
  }
  /**
   * <pre>
   * Actual provider-selected name, present only in a durable completion receipt.
   * </pre>
   *
   * <code>string published_name = 5;</code>
   * @param value The publishedName to set.
   */
  private void setPublishedName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    publishedName_ = value;
  }
  /**
   * <pre>
   * Actual provider-selected name, present only in a durable completion receipt.
   * </pre>
   *
   * <code>string published_name = 5;</code>
   */
  private void clearPublishedName() {

    publishedName_ = getDefaultInstance().getPublishedName();
  }
  /**
   * <pre>
   * Actual provider-selected name, present only in a durable completion receipt.
   * </pre>
   *
   * <code>string published_name = 5;</code>
   * @param value The bytes for publishedName to set.
   */
  private void setPublishedNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    publishedName_ = value.toStringUtf8();

  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferAck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.TransferAck prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code galaxybridge.v1.TransferAck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.TransferAck, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.TransferAck)
      com.xopmc.galaxybridge.protocol.v1.TransferAckOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.TransferAck.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string transfer_id = 1;</code>
     * @return The transferId.
     */
    @java.lang.Override
    public java.lang.String getTransferId() {
      return instance.getTransferId();
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @return The bytes for transferId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTransferIdBytes() {
      return instance.getTransferIdBytes();
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @param value The transferId to set.
     * @return This builder for chaining.
     */
    public Builder setTransferId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTransferId(value);
      return this;
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransferId() {
      copyOnWrite();
      instance.clearTransferId();
      return this;
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @param value The bytes for transferId to set.
     * @return This builder for chaining.
     */
    public Builder setTransferIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTransferIdBytes(value);
      return this;
    }

    /**
     * <code>uint64 confirmed_offset = 2;</code>
     * @return The confirmedOffset.
     */
    @java.lang.Override
    public long getConfirmedOffset() {
      return instance.getConfirmedOffset();
    }
    /**
     * <code>uint64 confirmed_offset = 2;</code>
     * @param value The confirmedOffset to set.
     * @return This builder for chaining.
     */
    public Builder setConfirmedOffset(long value) {
      copyOnWrite();
      instance.setConfirmedOffset(value);
      return this;
    }
    /**
     * <code>uint64 confirmed_offset = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfirmedOffset() {
      copyOnWrite();
      instance.clearConfirmedOffset();
      return this;
    }

    /**
     * <code>bool complete = 3;</code>
     * @return The complete.
     */
    @java.lang.Override
    public boolean getComplete() {
      return instance.getComplete();
    }
    /**
     * <code>bool complete = 3;</code>
     * @param value The complete to set.
     * @return This builder for chaining.
     */
    public Builder setComplete(boolean value) {
      copyOnWrite();
      instance.setComplete(value);
      return this;
    }
    /**
     * <code>bool complete = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearComplete() {
      copyOnWrite();
      instance.clearComplete();
      return this;
    }

    /**
     * <code>string failure_reason = 4;</code>
     * @return The failureReason.
     */
    @java.lang.Override
    public java.lang.String getFailureReason() {
      return instance.getFailureReason();
    }
    /**
     * <code>string failure_reason = 4;</code>
     * @return The bytes for failureReason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFailureReasonBytes() {
      return instance.getFailureReasonBytes();
    }
    /**
     * <code>string failure_reason = 4;</code>
     * @param value The failureReason to set.
     * @return This builder for chaining.
     */
    public Builder setFailureReason(
        java.lang.String value) {
      copyOnWrite();
      instance.setFailureReason(value);
      return this;
    }
    /**
     * <code>string failure_reason = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFailureReason() {
      copyOnWrite();
      instance.clearFailureReason();
      return this;
    }
    /**
     * <code>string failure_reason = 4;</code>
     * @param value The bytes for failureReason to set.
     * @return This builder for chaining.
     */
    public Builder setFailureReasonBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFailureReasonBytes(value);
      return this;
    }

    /**
     * <pre>
     * Actual provider-selected name, present only in a durable completion receipt.
     * </pre>
     *
     * <code>string published_name = 5;</code>
     * @return The publishedName.
     */
    @java.lang.Override
    public java.lang.String getPublishedName() {
      return instance.getPublishedName();
    }
    /**
     * <pre>
     * Actual provider-selected name, present only in a durable completion receipt.
     * </pre>
     *
     * <code>string published_name = 5;</code>
     * @return The bytes for publishedName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPublishedNameBytes() {
      return instance.getPublishedNameBytes();
    }
    /**
     * <pre>
     * Actual provider-selected name, present only in a durable completion receipt.
     * </pre>
     *
     * <code>string published_name = 5;</code>
     * @param value The publishedName to set.
     * @return This builder for chaining.
     */
    public Builder setPublishedName(
        java.lang.String value) {
      copyOnWrite();
      instance.setPublishedName(value);
      return this;
    }
    /**
     * <pre>
     * Actual provider-selected name, present only in a durable completion receipt.
     * </pre>
     *
     * <code>string published_name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublishedName() {
      copyOnWrite();
      instance.clearPublishedName();
      return this;
    }
    /**
     * <pre>
     * Actual provider-selected name, present only in a durable completion receipt.
     * </pre>
     *
     * <code>string published_name = 5;</code>
     * @param value The bytes for publishedName to set.
     * @return This builder for chaining.
     */
    public Builder setPublishedNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPublishedNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.TransferAck)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.TransferAck();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "transferId_",
            "confirmedOffset_",
            "complete_",
            "failureReason_",
            "publishedName_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u0003" +
              "\u0003\u0007\u0004\u0208\u0005\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.TransferAck> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.TransferAck.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.TransferAck>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.TransferAck)
  private static final com.xopmc.galaxybridge.protocol.v1.TransferAck DEFAULT_INSTANCE;
  static {
    TransferAck defaultInstance = new TransferAck();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TransferAck.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferAck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TransferAck> PARSER;

  public static com.google.protobuf.Parser<TransferAck> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

