// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: galaxybridge.proto
// Protobuf Java Version: 4.36.0

package com.xopmc.galaxybridge.protocol.v1;

/**
 * <pre>
 * Explicit user cancellation; authenticated channel ownership is checked by the receiver.
 * </pre>
 *
 * Protobuf type {@code galaxybridge.v1.TransferCancel}
 */
@com.google.protobuf.Generated
public  final class TransferCancel extends
    com.google.protobuf.GeneratedMessageLite<
        TransferCancel, TransferCancel.Builder> implements
    // @@protoc_insertion_point(message_implements:galaxybridge.v1.TransferCancel)
    TransferCancelOrBuilder {
  private TransferCancel() {
    transferId_ = "";
  }
  public static final int TRANSFER_ID_FIELD_NUMBER = 1;
  private java.lang.String transferId_;
  /**
   * <code>string transfer_id = 1;</code>
   * @return The transferId.
   */
  @java.lang.Override
  public java.lang.String getTransferId() {
    return transferId_;
  }
  /**
   * <code>string transfer_id = 1;</code>
   * @return The bytes for transferId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransferIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(transferId_);
  }
  /**
   * <code>string transfer_id = 1;</code>
   * @param value The transferId to set.
   */
  private void setTransferId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    transferId_ = value;
  }
  /**
   * <code>string transfer_id = 1;</code>
   */
  private void clearTransferId() {

    transferId_ = getDefaultInstance().getTransferId();
  }
  /**
   * <code>string transfer_id = 1;</code>
   * @param value The bytes for transferId to set.
   */
  private void setTransferIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    transferId_ = value.toStringUtf8();

  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.xopmc.galaxybridge.protocol.v1.TransferCancel prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Explicit user cancellation; authenticated channel ownership is checked by the receiver.
   * </pre>
   *
   * Protobuf type {@code galaxybridge.v1.TransferCancel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.xopmc.galaxybridge.protocol.v1.TransferCancel, Builder> implements
      // @@protoc_insertion_point(builder_implements:galaxybridge.v1.TransferCancel)
      com.xopmc.galaxybridge.protocol.v1.TransferCancelOrBuilder {
    // Construct using com.xopmc.galaxybridge.protocol.v1.TransferCancel.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string transfer_id = 1;</code>
     * @return The transferId.
     */
    @java.lang.Override
    public java.lang.String getTransferId() {
      return instance.getTransferId();
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @return The bytes for transferId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTransferIdBytes() {
      return instance.getTransferIdBytes();
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @param value The transferId to set.
     * @return This builder for chaining.
     */
    public Builder setTransferId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTransferId(value);
      return this;
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransferId() {
      copyOnWrite();
      instance.clearTransferId();
      return this;
    }
    /**
     * <code>string transfer_id = 1;</code>
     * @param value The bytes for transferId to set.
     * @return This builder for chaining.
     */
    public Builder setTransferIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTransferIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:galaxybridge.v1.TransferCancel)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.xopmc.galaxybridge.protocol.v1.TransferCancel();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "transferId_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.xopmc.galaxybridge.protocol.v1.TransferCancel> parser = PARSER;
        if (parser == null) {
          synchronized (com.xopmc.galaxybridge.protocol.v1.TransferCancel.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.xopmc.galaxybridge.protocol.v1.TransferCancel>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:galaxybridge.v1.TransferCancel)
  private static final com.xopmc.galaxybridge.protocol.v1.TransferCancel DEFAULT_INSTANCE;
  static {
    TransferCancel defaultInstance = new TransferCancel();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TransferCancel.class, defaultInstance);
  }

  public static com.xopmc.galaxybridge.protocol.v1.TransferCancel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TransferCancel> PARSER;

  public static com.google.protobuf.Parser<TransferCancel> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

