#!/usr/bin/env python3
"""Regenerate shipping declarations and the reference matrix; never translate or add catalogs."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs/localization"
manifest = json.loads((DOCS / "system-languages.json").read_text())
locales = manifest["locales"]
ids = [row["id"] for row in locales]
assert len(set(ids)) == len(ids) and "en" in ids
assert manifest["fallbackLanguage"] == "en"
assert manifest["shippingScope"] == "user-selected-popular-languages"
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true", help="fail if generated declarations are stale")
args = parser.parse_args()

info_path = ROOT / "macos/GalaxyBridgeMac/Info.plist"
info = info_path.read_text()
array = "<key>CFBundleLocalizations</key>\n\t<array>\n" + "".join(f"\t\t<string>{code}</string>\n" for code in ids) + "\t</array>"
info, count = re.subn(r"<key>CFBundleLocalizations</key>\s*<array>.*?</array>", lambda _: array, info, flags=re.S)
assert count == 1
info, count = re.subn(r"(<key>CFBundleDevelopmentRegion</key>\s*<string>).*?(</string>)", r"\g<1>en\2", info, flags=re.S)
assert count == 1
xml = '<?xml version="1.0" encoding="utf-8"?>\n<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n'
xml += "".join(f'    <locale android:name="{code}" />\n' for code in ids) + '</locale-config>\n'

def catalog_for(locale):
    tag = locale.replace("_", "-")
    language = tag.split("-")[0]
    if language == "zh":
        return "zh-Hant" if any(x in tag.split("-") for x in ("Hant", "TW", "HK", "MO")) else "zh-Hans"
    return language if language in ids else "en"

lines = ["# Shipping language and fallback matrix", "",
    "The user's explicit 2026-09-13 scope change supersedes the earlier all-system-language requirement.",
    "Ship ten languages in eleven catalogs: English, Russian, German, French, Spanish, Portuguese, Arabic, Chinese (Simplified and Traditional), Japanese and Korean.",
    "Portuguese regions use `pt`. Other unsupported-only system preferences use English (`en`). A supported later preference is still selected by the operating system's normal ordered matching.", "",
    "Generated by `scripts/generate-localization-config.py` from the selected shipping manifest and historical reference inventories. The system locale rows below are not claims of separate translations.", "",
    "| Source | System locale | Result for this sole preference |", "| --- | --- | --- |"]
inventory = json.loads((DOCS / "macos-system-language-inventory.json").read_text())
aosp = re.findall(r"^\s*([a-z]+(?:_[A-Za-z]+)+)\s*(?:\\)?\s*$", (DOCS / "aosp-languages-default.mk").read_text(), re.M)
for source, values in [("macOS " + inventory["systemVersion"], inventory["localizations"]), ("AOSP reference", aosp)]:
    for locale in values:
        if locale in ("ar_XB", "en_XA"): continue
        target = catalog_for(locale)
        fallback = target == "en" and locale.replace("_", "-").split("-")[0] != "en"
        result = "English fallback (`en`)" if fallback else f"`{target}`"
        lines.append(f"| {source} | `{locale}` | {result} |")
outputs = {
    info_path: info,
    ROOT / "android/app/src/main/res/xml/locales_config.xml": xml,
    DOCS / "system-language-matrix.md": "\n".join(lines) + "\n",
}
stale = []
for path, contents in outputs.items():
    if not path.exists() or path.read_text() != contents:
        stale.append(str(path.relative_to(ROOT)))
        if not args.check: path.write_text(contents)
if args.check and stale:
    raise SystemExit("Stale localization configuration: " + ", ".join(stale))
print(("PASS" if args.check else "Generated") + f" selected language configuration: {len(ids)} catalogs, English fallback")
