#!/usr/bin/env bash
set -euo pipefail
GB_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GB_NATIVE_COMPONENT=backend-tests
source "$GB_ROOT/scripts/native-build-env.sh"
if [[ "${1:-}" == "--export-fixtures" ]]; then
  [[ $# == 2 ]] || exit 2
  GB_FACTORY="$GB_ROOT/macos/GalaxyBridgeMacKeyboardTests/QuicCodecFixtureFactory.swift"
  mkdir -p "$GB_BUILD_DIR/test-artifacts" "$2"
  "$(xcrun --find swiftc)" -parse-as-library -target arm64-apple-macosx14.0 -sdk "$(xcrun --show-sdk-path)" "$GB_FACTORY" "$GB_ROOT/native/galaxybridge-quic-backend/tests/ExportStockFixture.swift" -o "$GB_BUILD_DIR/test-artifacts/export-stock-fixture"
  "$GB_BUILD_DIR/test-artifacts/export-stock-fixture" --output "$2"
  exit $?
fi
export GB_QUIC_TEST_PRODUCER="${GB_QUIC_TEST_PRODUCER:-${GB_PRODUCER_JAR:-$GB_ROOT/build/native/scrcpy/scrcpy-server-4.1-gb-sync.1}}"
if [[ ! -f "$GB_QUIC_TEST_PRODUCER" ]]; then
    GB_OUTPUT_DIR="$(dirname "$GB_QUIC_TEST_PRODUCER")" GB_BUILD_DIR="$GB_BUILD_DIR/scrcpy" bash "$GB_ROOT/scripts/build-scrcpy-gb-sync.sh"
fi
export GB_PRODUCER_SHA256="$(shasum -a 256 "$GB_QUIC_TEST_PRODUCER" | awk '{print $1}')"
if [[ "${1:-}" == "--ffi" ]]; then
  shift
  [[ $# == 0 ]] || exit 2
  "$GB_CARGO" build "${GB_CARGO_NETWORK[@]}" --features qa --manifest-path "$GB_ROOT/native/galaxybridge-quic-backend/Cargo.toml" --target aarch64-apple-darwin
  GB_OUT="$CARGO_TARGET_DIR/aarch64-apple-darwin/debug"
  /usr/bin/clang -std=c11 -D_DARWIN_C_SOURCE -Wall -Wextra -Werror -I "$GB_ROOT/native/galaxybridge-quic-backend/include" "$GB_ROOT/native/galaxybridge-quic-backend/tests/ffi_contract.c" "$GB_OUT/libgalaxybridge_quic_backend.a" -lc++ -liconv -framework Security -framework CoreFoundation -framework SystemConfiguration -o "$GB_OUT/gb-quic-backend-c-test"
  "$GB_OUT/gb-quic-backend-c-test" "$GB_OUT/gb-quic-backend"
  exit $?
fi
# Codec fixtures are generated by the source factory on the build host, never
# imported from a private evidence directory.
export GB_QUIC_TEST_FIXTURES="${GB_QUIC_TEST_FIXTURES:-$GB_BUILD_DIR/fixtures}"
if [[ ! -f "$GB_QUIC_TEST_FIXTURES/h264.stock" || ! -f "$GB_QUIC_TEST_FIXTURES/hevc.stock" || ! -f "$GB_QUIC_TEST_FIXTURES/aac.stock.sha256" ]]; then
    mkdir -p "$GB_BUILD_DIR"
    GB_QUIC_TEST_FIXTURES=$(mktemp -d "$GB_BUILD_DIR/fixtures.XXXXXX")
    export GB_QUIC_TEST_FIXTURES
    bash "$0" --export-fixtures "$GB_QUIC_TEST_FIXTURES"
fi
if [[ -z "${GB_QUIC_ROUTE_TEST_DESTINATION:-}" ]]; then
    export GB_QUIC_ROUTE_TEST_DESTINATION="$(python3 "$GB_ROOT/scripts/native-test-route.py")"
fi
"$GB_CARGO" test "${GB_CARGO_NETWORK[@]}" --features qa --manifest-path "$GB_ROOT/native/galaxybridge-quic-backend/Cargo.toml" --target aarch64-apple-darwin "$@" -- --test-threads=1
