import Foundation

enum MacClipboardPayloadKind: Sendable {
    case text
    case url
    case png
}

struct MacClipboardPayloadCandidate: Sendable, Equatable {
    let kind: MacClipboardPayloadKind
    let content: Data

    var scrcpyText: String? {
        switch kind {
        case .text, .url: String(data: content, encoding: .utf8)
        case .png: nil
        }
    }
}

enum MacClipboardPayloadPolicy {
    static let maximumTextBytes = 256 * 1024
    static let maximumImageBytes = 4 * 1024 * 1024

    private static let excludedPasteboardTypes: Set<String> = [
        "org.nspasteboard.concealedtype",
        "org.nspasteboard.transienttype",
        "org.nspasteboard.autogeneratedtype",
        "com.agilebits.onepassword",
        "com.agilebits.onepassword.private",
    ]

    static func candidate(
        pasteboardTypes: [String],
        text: String?,
        png: Data?
    ) -> MacClipboardPayloadCandidate? {
        let normalizedTypes = Set(pasteboardTypes.map { $0.lowercased() })
        guard excludedPasteboardTypes.isDisjoint(with: normalizedTypes) else { return nil }

        if let png {
            guard !png.isEmpty, png.count <= maximumImageBytes else { return nil }
            return MacClipboardPayloadCandidate(kind: .png, content: png)
        }

        guard let text, let content = text.data(using: .utf8),
              !content.isEmpty, content.count <= maximumTextBytes
        else { return nil }
        return MacClipboardPayloadCandidate(
            kind: isWebURL(text) ? .url : .text,
            content: content
        )
    }

    private static func isWebURL(_ value: String) -> Bool {
        guard let components = URLComponents(string: value.trimmingCharacters(in: .whitespacesAndNewlines)),
              let scheme = components.scheme?.lowercased(),
              scheme == "http" || scheme == "https"
        else { return false }
        return components.host?.isEmpty == false
    }
}
